### ISSUE TITLE
How to install custom scripts requiring other npm modules when using the Docker image?

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/hubot-rocketchat#103]
For instance adding remind.coffee from the github hubot scripts requires lodash, moment and chrono-mode... It would be great to add for instance a EXTERNAL_DEPENDENCIES environment variable passed to npm install in the image.

**Comment by geekgonecrazy** [comment]
@jmatsushita any script you include via EXTERNAL_SCRIPTS have their npm modules installed at startup.  So as long as those dependencies are present in the package.json of that script those will be installed.

**Comment by jmatsushita** [comment]
Yes but I'm talking about custom scripts which are added per these instructions https://github.com/RocketChat/hubot-rocketchat#custom-scripts

**Comment by geekgonecrazy** [comment]
@jmatsushita if you ran npm install in that scripts folder I believe it will be able to resolve the dependencies.

**Comment by jmatsushita** [comment]
You're right but I thought that adding a line in your Dockerfile would add
a feature upstream and therefore solve the problem for any future person
trying to deploy custom scripts that way :)

**Comment by geekgonecrazy** [comment]
Possibly.  We can take a look.  We want to keep our dockerfile as simple as possible. The more complexities added, the harder it is to maintain

**Comment by Sing-Li** [comment]
No need to further complicate the already super-complicated-to-configure-properly container.    Best to  link a  docker volume to the container dir `/home/hubot/script` when you `docker run`; and add whatever script plus dependencies you like in the (now) external scripts directory.

**Comment by jmatsushita** [comment]
Ok I'll just fork it! Wish there was anything other well maintained docker
image for hubot...

**Comment by jmatsushita** [comment]
Actually https://github.com/RocketChat/hubot-rocketchat/issues/103#issuecomment-187797653 doesn't work given that the custom scripts are the old school standalone coffee files without the package.json. I've added a EXTERNAL_DEPENDENCIES environment variable in a fork. (Not  HUBOT_DEPENDENCIES despite what the commit message says).

It can be use by adding npm package names that coffee script depend on in a comma separated list.

**Comment by pierreozoux** [comment]
Oh man, what a pain!
There was easier than forking :)
@jmatsushita you could have put the dependency in `EXTERNAL_SCRIPTS` :)

but I agree, it is a major PITA! It is not as easy as git clone any npm module inside `scripts` folder.
I guess this is also due to the fact that hubot is switching from scripts to npm module, nad everyhting is borked (doc, here...) I just spent 2 hours installing hubot-trello... (also because there are 20 different one, and the official one doesn't have the latest version on npm...)

**Comment by jmatsushita** [comment]
@pierreozoux Not sure we were facing the same issue. I needed old scripts that depend on npm modules to be installed without having to change own docker image for each script. Scripts in EXTERNAL_SCRIPTS are meant to use the new format which mean that they can be npm installed. Old scripts (simple coffee files usually) might have node dependencies which need to be installed manually, I added EXTERNAL_DEPENDENCIES to npm install these dependencies.

i.e. if you want to use the [hackernews.coffee](https://github.com/github/hubot-scripts/blob/master/src/scripts/hackernews.coffee) script which depends on the `nodepie` npm package then you can mount the coffee file in `/home/hubot/scripts` and add `EXTERNAL_DEPENDENCIES=nodepie` when starting the docker container without having to create and maintain your own docker image.

Sounds like your problem was more related to the
> already super-complicated-to-configure-properly image

:)

**Comment by pierreozoux** [comment]
No, just put: `nodepie` in `EXTERNAL_SCRIPTS`. It's hacky, but at the
end it is just `npm install`ed like the rest :)

On 02-05-2016 18:19, Jun Matsushita wrote:
> @pierreozoux <https://github.com/pierreozoux> Not sure we were facing
> the same issue. I needed old scripts that depend on npm modules to be
> installed without having to change own docker image for each script.
> Scripts in EXTERNAL_SCRIPTS are meant to use the new format which mean
> that they can be npm installed. Old scripts (simple coffee files
> usually) might have node dependencies which need to be installed
> manually, I added EXTERNAL_DEPENDENCIES to npm install these dependencies.
> 
> i.e. if you want to use the hackernews.coffee
> <https://github.com/github/hubot-scripts/blob/master/src/scripts/hackernews.coffee>
> script which depends on the |nodepie| npm package then you can mount the
> coffee file in |/home/hubot/scripts| and add
> |EXTERNAL_DEPENDENCIES=nodepie| when starting the docker container
> without having to create and maintain your own docker image.
> 
> Sounds like your problem was more related to the
> 
>     already super-complicated-to-configure-properly image
> 
> :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/hubot-rocketchat/issues/103#issuecomment-216281896>
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by jmatsushita** [comment]
Oh man thanks 👍 Why didn't I think of that :)

**Comment by geekgonecrazy** [comment]
@pierreozoux oh yeah!  Idk why I didn't think of that as a work around!   Thanks for sharing :+1:
