### ISSUE TITLE
User id required instead of user name in HUBOT_AUTH_ADMIN

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/hubot-rocketchat#105]
Hi there,

When using the user name with hubot-auth for the HUBOT_AUTH_ADMIN environment variable (like `HUBOT_AUTH_ADMIN=jun` the script doesn't correctly recognise me as admin and I need to use the Mongo `_id` field and then it works...

Cheers,

Jun

**Comment by whatashot** [comment]
Also looking for the same solution for HUBOT_AUTH, did you find a solution?

**Comment by unixfox** [comment]
Any news ?

**Comment by jamie-hughes** [comment]
I have created a script which will allow you to use the !userid command to display your user id.
You can find it here: https://github.com/jamie-hughes/hubot/blob/master/scripts/UserID.coffee
Hope this helps!

**Comment by geekgonecrazy** [comment]
So from an adapter point of view we would need to take the user specified and find the userid for it.  Or... We would need to try and override that function in the adapter to compare on username and not on userid.

**Comment by timkinnane** [comment]
I'm going to close this because it's quite old and not sure its relevant anymore. Please comment to reopen if required.
