### ISSUE TITLE
Ability to see presence

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/hubot-rocketchat#106]
We need the bot to be able to subscribe to presence of users.  So scripts like hubot-tell can be modified to alert based on entering / leaving a room, or online / offline.

**Comment by Sing-Li** [comment]
Seems we get some interest in this once every year.   Following up on discussion in https://demo.rocket.chat  in the #dev channel.

What hubot users generally want/expect is:

-  whenever a user, on any device, click on to view a channel ... the enter event fires on the channel he is viewing, and the leave event fires on the channel he was viewing previously

Unfortunately not aligned with our notion of enter, leave, online, offline or presence in any way.

**Comment by engelgabriel** [comment]
I don't agree, I have never seen a use case for firing an hubot event whenever a user, on any device, click on to view a channel.

**Comment by engelgabriel** [comment]
Same as https://github.com/slackapi/hubot-slack/issues/58

**Comment by Sing-Li** [comment]
Interesting.  It would be indeed good to get some expected use cases to see what is actually expected then.

**Comment by makeitcount** [comment]
@engelgabriel This does makes sense to have something where bot can great everyone who joins and guide on how to use the platform. Is there any development on this issue? How should I go about it to implement solution for my use case.

**Comment by geekgonecrazy** [comment]
just FYI a message with the type: `uj` is sent in the channel when a user joins the channel.

**Comment by timkinnane** [comment]
Closing this because the [`.enter` and `.leave`](https://hubot.github.com/docs/scripting/#entering-and-leaving) listeners have been implemented and there's no clear use case for anything further.

**Comment by timkinnane** [comment]
@opensimworld Sorry for delay. Please report a new issue with some specific info, like your version number and sample code if possible. The enter callback should definitely work on user's first room join if the bot is active in the room too, so if that's not working for you, it's a new and separate bug.
