### ISSUE TITLE
Why there's no respond?

### ISSUE THREAD

**Issue by poxzlm** [RocketChat/hubot-rocketchat#110]
Hi there,
I have set up this amazing hubot-rocketchat using docker.
Here's the starting log:
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: bot
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Connecting To: rocketchat.datayes.com:3000
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Successfully connected!
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO uqerboys
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Logging In
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Successfully Logged In
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Looking up Room ID for: uqerboys
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Joining Room: 7dxu3tSNzm7rP32T7
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO rid:  [ '7dxu3tSNzm7rP32T7' ]
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO All rooms joined.
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Successfully joined room: 7dxu3tSNzm7rP32T7
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Subscribing to Room: 7dxu3tSNzm7rP32T7
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO All subscriptions ready.
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Successfully subscribed to room: 7dxu3tSNzm7rP32T7
[Tue Apr 05 2016 09:41:46 GMT+0000 (UTC)] INFO Setting up reactive message list...

But I can't get any respond by the command: rocket help
Here's the log:
[Tue Apr 05 2016 09:55:27 GMT+0000 (UTC)] INFO Message received with ID 67eCvGDFzE8XmMdRX
[Tue Apr 05 2016 09:55:27 GMT+0000 (UTC)] INFO Message receive callback id xgpeyRrGSNWHm6KGg ts Tue Apr 05 2016 09:55:28 GMT+0000 (UTC)
[Tue Apr 05 2016 09:55:27 GMT+0000 (UTC)] INFO [Incoming] xiaowen.liu: rocketbot help
[Tue Apr 05 2016 09:55:27 GMT+0000 (UTC)] INFO Message sent to hubot brain.

**Comment by Sing-Li** [comment]
Try  `bot help`  😃

**Comment by poxzlm** [comment]
@Sing-Li Thank you! Then you guys should update the document?

**Comment by geekgonecrazy** [comment]
@poxzlm bot help isn't necessarily included in every install.  Depends on how you set it up.

But sure, we can look at mentioning ways of verifying the bot is alive 😄
