### ISSUE TITLE
Bot cannot connect via reverse proxy

### ISSUE THREAD

**Issue by twhiting** [RocketChat/hubot-rocketchat#113]
Set all my variables but my bot will not connect to my server.  Any thoughts? 

```
INFO Starting Rocketchat adapter....
INFO Once connected to rooms I will respond to the name: FrxBot
INFO Connecting To: chat.<my domain>.com:443
```

Running on Windows.

**Comment by geekgonecrazy** [comment]
@twhiting seeing you have port 443 I assume ssl is involved?  If so you should specify the url https://<my domain>.com

Also we've noticed some have issues connecting via ssl.  Something to do with certificate

**Comment by twhiting** [comment]
I did specify https://<domain>.com I'm pretty sure it just cuts out http/https from the front of the url you give it.  Do you remember what exactly about? I'd love to get this figured out as i'm trying to implement chatops into our company but ran into this issue and have since been in a stand still.

**Comment by twhiting** [comment]
I found a way to work around this, finally...  I'll leave this ticket open b/c the ssl problem.

Since i'm running the hubot in my local network I simply pointed it to http://<rocket.chat internal ip>:3000 and it works now.

**Comment by geekgonecrazy** [comment]
We need to verify this is still happening, and narrow it down to what cases it happens vs doesn't happen.

**Comment by geekgonecrazy** [comment]
Actually closing in favor of #95
