### ISSUE TITLE
Log messages are duplicated when using ROCKETCHAT_ROOM

### ISSUE THREAD

**Issue by jmaslin** [RocketChat/hubot-rocketchat#121]
When using a list of rooms on the `ROCKETCHAT_ROOM` environment variable, log messages are repeated for each room. For example, if you are listening on 7 channels, you will have 7 log messages for each new message. Each message is received with a new ID, but has the same callback ID.

Using `LISTEN_ON_ALL_PUBLIC` does not cause the log messages to repeat. Commands responses only happen once, it just seems like it is the logs that are being duplicated.

**Comment by geekgonecrazy** [comment]
Can you verify that this is still happening?  Shouldn't any longer with Rocket.Chat version 0.37.0 and adapter version v1.0.3

**Comment by leonardorocc0** [comment]
my hubot rocketchat duplicates messages in rocket chat as shown below
![image](https://user-images.githubusercontent.com/31746843/38715383-304c9faa-3eb1-11e8-91f2-af17adfa5061.png)

**Comment by timkinnane** [comment]
I think this has been resolved with updated streamer in Rocket.Chat.
