### ISSUE TITLE
Permissions issues running yo 

### ISSUE THREAD

**Issue by fredhampton** [RocketChat/hubot-rocketchat#122]
Trying to install hubot and receiving the following error when trying to run yo  

/Rocket.Chat/myhubot# yo hubot --adapter="rocketchat"
/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:53
                                throw err;
                                      ^
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

**Comment by geekgonecrazy** [comment]
the file is in root's home folder, are you running as root?

**Comment by fredhampton** [comment]
I am running as root 

 

On May 27, 2016 at 12:16:30 PM, Aaron Ogle (notifications@github.com) wrote:

the file is in root's home folder, are you running as root?

**Comment by Againstreality** [comment]
chmod -R 775 on .config/configstore should fix this. Got the same Problem. I dont understand why it needs group rights but it works

**Comment by geekgonecrazy** [comment]
Thanks for providing the solution on this @Againstreality.  @fredhampton if that doesn't work, feel free to open it back up.

**Comment by FibreFoX** [comment]
To write it down somewhere, while I tried to setup a local VM for hubot-development this issue was present for me too. I ended up in calling `yo hubot ` as non-root. Maybe this is something to mention inside the docs, for building as NON-root is the prefered way?

**Comment by KyleStay** [comment]
@FibreFoX were you able to accomplish this within a shell script? If so, how?
