### ISSUE TITLE
HUBOT not connecting

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/hubot-rocketchat#123]
Using the latest Rocket.chat 0.32
Using the latest Docker image to connect

[Tue May 31 2016 08:15:37 GMT+0000 (UTC)] INFO Successfully Logged In
[Tue May 31 2016 08:15:37 GMT+0000 (UTC)] INFO Looking up Room ID for: GENERAL
[Tue May 31 2016 08:15:37 GMT+0000 (UTC)] ERROR Unable to get room id: {"error":"error-not-allowed","reason":"Not allowed","details":{"method":"getRoomIdByNameOrId"},"message":"Not allowed [error-not-allowed]","errorType":"Meteor.Error"} Reason: Not allowed

**Comment by Sing-Li** [comment]
make sure you have created your "bot user" on the chat server, and logged in at least once with that user - and have joined GENERAL.

**Comment by TheReal1604** [comment]
Check your docker-compose file against the example i added to the docs:

https://github.com/RocketChat/hubot-rocketchat/pull/138/commits/503db8b6592ad7bb0b697f8e0ef276bf5895c187

Got the same error, after adjusting the compose file like in the example, all was working again.

**Comment by geekgonecrazy** [comment]
@TheReal1604 so is this hubot section in the same docker-compose file as rocketchat?

**Comment by CnytSntrk** [comment]
@Sing-Li Hi. I have created bot user on the chat server and have loged in but there is no room as general. I thought thats way my bot cannot connect to room general. Any idea ?
When i login with new user general room is there but with bot it doesn't

**Comment by geekgonecrazy** [comment]
Sounds like the bot user just didn't have the bot role or the correct permission on the role.  

So make sure the user you are logging in via hubot has the bot role.  Then, on the bot role make sure you add the permission `view-c-room`

Going to go ahead and close this issue out.  Your issue is related to not being able to join the room.  If that doesn't work please open a new issue regarding that.

**Comment by edzillion** [comment]
FYI I got this error when I connected the bot and set a non-existent room in the `ROCKETCHAT_ROOM` environment variable. All I had to do was create the room and then try again and it worked fine.

**Comment by subesokun** [comment]
Don't know why but calling `robot.messageRoom(user.id, 'text')` (i.e. send a direct message to a user) doesn't work anymore for me in the latest version in combination with Hubot3. It throws always the error
```
ERROR [getRoomIdByNameOrId] Error: { isClientSafe: true,
  error: 'error-not-allowed',
  reason: 'Not allowed',
  details: { method: 'getRoomIdByNameOrId' },
  message: 'Not allowed [error-not-allowed]',
  errorType: 'Meteor.Error' }
```
The bot has the `view-c-room` permission but as I'm sending the message to a direct channel I'm guessing that this is not the problem.

Luckily I was able to work around this issue by using `robot.adapter.sendDirect({user}, 'text')` but it doesn't feel right...

**Comment by animator013** [comment]
Doesn't work for me either on version 0.68.3. Only in public rooms. In private rooms bot doesn't respond and if i set the primary room as private room, it won't even connect with the error stated here.
