### ISSUE TITLE
hubot never connects if started (slightly) before Rocket.Chat 

### ISSUE THREAD

**Issue by iroes** [RocketChat/hubot-rocketchat#131]
The lastest log entries are:
```
[Sat Jun 04 2016 11:40:53 GMT+0200 (CEST)] INFO Starting Rocketchat adapter...
[Sat Jun 04 2016 11:40:53 GMT+0200 (CEST)] INFO Once connected to rooms I will respond to the name: WHATEVER
[Sat Jun 04 2016 11:40:53 GMT+0200 (CEST)] INFO Connecting To: HOSTNAME:PORT
```
And here remains forever.

It can be a common issue after a reboot if both hubot and Rocket.Chat are on the same server (Rocket.Chat's loading is slower). Reloading hubot manually solves it, but not permanently. It needs to be done after each reboot. So it's probably related to issue #100 

I checked the source for the `RocketChatDriver` constructor, and I think it can be solved by using another Asteroid event for the callback: `reconnected`. 

So that the code looks like this:

```coffeescript
class RocketChatDriver
	constructor: (url, ssl, @logger, cb) ->
		if ssl is  'true'
			sslenable = true
		else
			sslenable = false
		@asteroid = new Asteroid(url, sslenable)
		@asteroid.on 'connected', ->
			cb()
		@asteroid.on 'reconnected', ->
			cb()
```

**Comment by geekgonecrazy** [comment]
@iroes awesome!  Would you be able to open a pull request with this change so you'd be credited with the fix?  Otherwise I can do it and mention you in the commit

**Comment by iroes** [comment]
Ok @geekgonecrazy, done. Thanks!

**Comment by geekgonecrazy** [comment]
Thanks!  Tagging a new release now 👍
