### ISSUE TITLE
Hubot not listening to any rooms

### ISSUE THREAD

**Issue by pasmon** [RocketChat/hubot-rocketchat#134]
For some reason, our Hubot is not responding to anything this week (our cloud instance hosting Rocket.Chat and Hubot is terminated and started automatically once every weekend). Today I updated Rocket.Chat to the latest version 0.33.0, and unfortunately I didn't check if Hubot worked properly with the older, 0.31.0 version today - definitely it worked with that version a week ago.

Settings:
ROCKETCHAT_URL=localhost:3000
ROCKETCHAT_ROOM=''
LISTEN_ON_ALL_PUBLIC=true

The logs show that something has changed in the way Hubot connects to rooms, specifically it gets stuck to connecting to room "__my_messages__" (I don't remember seeing that earlier). Also, I believe I have seen mentions of Hubot connecting to "GENERAL" room, and here it is absent.

> Jun 13 10:12:03 euca-- hubot[17012]: Hubot@0.0.0 /home_local/chatbot/hubot
> Jun 13 10:12:03 euca-- hubot[17012]: +-- bluebird@3.4.0  extraneous
> Jun 13 10:12:03 euca-- hubot[17012]: +-- hubot-daily-comic@0.0.1  extraneous
> Jun 13 10:12:03 euca-- hubot[17012]: +-- hubot-darksky@1.0.2  extraneous
> Jun 13 10:12:03 euca-- hubot[17012]: +-- hubot-gitlab-hooks@0.5.0
> Jun 13 10:12:03 euca-- hubot[17012]: +-- hubot-gitsy@0.8.3  extraneous
> Jun 13 10:12:03 euca-- hubot[17012]: +-- hubot-gocd@0.0.6  extraneous
> Jun 13 10:12:03 euca-- hubot[17012]: +-- hubot-jenkins-notifier@0.1.5  extraneous
> Jun 13 10:12:03 euca-- hubot[17012]: +-- hubot-jira-linkifier@0.0.1  extraneous
> Jun 13 10:12:03 euca-- hubot[17012]: +-- hubot-lunch-at-amica@1.0.2  extraneous
> Jun 13 10:12:03 euca-- hubot[17012]: +-- hubot-proxy-loader@0.0.1  extraneous
> Jun 13 10:12:03 euca-- hubot[17012]: `-- hubot-voting@1.0.0  extraneous
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO Starting Rocketchat adapter version 1.0.1...
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO Once connected to rooms I will respond to the name: hubot
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] WARNING No services ROCKETCHAT_ROOM provided to Hubot, using
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO Connecting To: localhost:3000
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO Successfully connected!
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO Logging In
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO Successfully Logged In
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO rid:  []
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO All rooms joined.
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO Preparing Meteor Subscriptions..
> Jun 13 10:12:04 euca-- hubot[17012]: [Mon Jun 13 2016 10:12:04 GMT+0300 (EEST)] INFO Subscribing to Room: __my_messages__

Is the Rocket.Chat update the issue here?

**Comment by geekgonecrazy** [comment]
Please see the README and release notes for the adapter.  As with most software probably a good idea to specify the version of the adapter manually.  V1.x is not compatible with Rocket.Chat v0.33 and newer.  Please use an older version of the adapter.

Sorry about the inconvenience

**Comment by pasmon** [comment]
Thanks for the heads up! I got Hubot working by using the older version of the adapter.
