### ISSUE TITLE
Rocket.Chat 0.34 Hubot-rocketchat 1.0.1 doesn't work

### ISSUE THREAD

**Issue by beauraF** [RocketChat/hubot-rocketchat#135]
Hello,

Since the update Rocket.Chat 0.34 abd Hubot-rocketchat 1.0.1, it does not receive any messages.

Here are the logs :

> Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO Starting Rocketchat adapter version 1.0.1...
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO Once connected to rooms I will respond to the name: Jeeves
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] WARNING No services ROCKETCHAT_URL provided to Hubot, using localhost:3000
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO Connecting To: localhost:3000
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO Successfully connected!
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO Logging In
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO Successfully Logged In
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO rid:  []
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO All rooms joined.
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO Preparing Meteor Subscriptions..
Jun 15 10:43:02 sd-91132 hubot[19686]: [Wed Jun 15 2016 10:43:02 GMT+0200 (CEST)] INFO Subscribing to Room: __my_messages__

Someone encounter the same problems ?
Did I miss something?

**Comment by Sing-Li** [comment]
Sorry @beauraF -  the README has been pre-updated with TOTALLY INACCURATE information.

Please continue to use 0.1.4 of hubot adapter with 0.34.0 - and until further notice.  DO NOT use the 1.0.x series.

**Comment by beauraF** [comment]
No worries Sing- Li.
I rollback on 0.1.4.

Thank you for your quick response and thank you for your work!

See you soon. Have a nice day. :)
