### ISSUE TITLE
Adapter doesn't receive media / attachment messages

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/hubot-rocketchat#139]
Hubot adapter is (AFAIK) unable to process message objects with attachments.
The message object below is what's currently received when I sent a DM to the bot with an image attachment. The message text is empty other than the auto prepended name. I've also tried capturing attachment messages in non-DM rooms and the text is completely empty.

```
message:
      TextMessage {
        user: [Object],
        text: 'Hubot ',
        id: 'Lx8WhdADN7oxKQhFX',
        done: false,
        room: 'ew8pCDwTTJGi6m5mno7tkCdvbCxScK5xHR' } } }
```

**Comment by geekgonecrazy** [comment]
@timkinnane have you tried looking on the `msg.message` object?

**Comment by timkinnane** [comment]
@geekgonecrazy Yeah I was pretty sure I looked through all the properties. Are you saying it should be there?

**Comment by geekgonecrazy** [comment]
It should be on that message object.  Because we essentially drop our
message object as is in the adapter

**Comment by ngenerio** [comment]
@geekgonecrazy I did a quick look of what is going on. The `newmsg` we get from the `setupReactiveMessageList` [here](https://github.com/RocketChat/hubot-rocketchat/blob/v0.1.4/src/rocketchat.coffee#L132) looks like this:

```json
{
  "rid": "L5vn23nm6zZefHkqktrgGoxKphoXvPJqD5",
  "msg": "",
  "file": {
    "_id": "k6zgdvow3bcK3D39y"
  },
  "groupable": false,
  "attachments": [
    {
      "title": "File Uploaded: 1-4FCAIgmJa8BuildjlnsDeA.png",
      "title_link": "/file-upload/k6zgdvow3bcK3D39y/1-4FCAIgmJa8BuildjlnsDeA.png",
      "title_link_download": true,
      "image_url": "/file-upload/k6zgdvow3bcK3D39y/1-4FCAIgmJa8BuildjlnsDeA.png",
      "image_type": "image/png",
      "image_size": 72753,
      "image_dimensions": {
        "width": 600,
        "height": 253
      }
    }
  ],
  "ts": {
    "$date": 1468228562436
  },
  "u": {
    "_id": "L5vn23nm6zZefHkqk",
    "username": "eugene"
  },
  "_id": "7pXcDQxoHBmaxiitC"
}
```

for messages with attachments. However, there is no check for the [presence of an attachment or file   on the message object](https://github.com/RocketChat/hubot-rocketchat/blob/v0.1.4/src/rocketchat.coffee#L142,L157). Hence the assumption that all the incoming messages will have a truthy `msg` property.

Will be glad to make a pull request to resolve this issue.

cc: @timkinnane

**Comment by geekgonecrazy** [comment]
@ngenerio We definitely welcome a PR to fix this 👍

**Comment by timkinnane** [comment]
Thanks @ngenerio. Sorry I never replied @geekgonecrazy, I was getting back to this today but it looks like Eugene fixed it. :D Hoping we can get that PR through quickly.

**Comment by ngenerio** [comment]
@geekgonecrazy I based the attachment work on [v0.1.4](https://github.com/RocketChat/hubot-rocketchat/tree/v0.1.4). So that it can be an early fix for users working with v0.1.x.

**Comment by geekgonecrazy** [comment]
@ngenerio perfect.  Yeah i'm debatting how we should handle that.  I guess we keep under the v0.1.x scheme of things for now.

I'll discuss a bit with the team and figure out how we can get things on the right track. 👍

**Comment by ngenerio** [comment]
That would be great. But you can check out the [attachment-support](https://github.com/ngenerio /hubot-rocketchat/tree/attachment-support) branch for now.

**Comment by ngenerio** [comment]
@geekgonecrazy I think we should go by the v0.1.x to support those using that version. Moreover, the README advices to use the v0.1.x versions for now as the work in v1.x.x is experimental.

**Comment by ngenerio** [comment]
@geekgonecrazy I also added the attachment support in the master branch. Hope this clears issues going forward with the master branch. Also have the [attachment-support](https://github.com/ngenerio/hubot-rocketchat/tree/attachment-support) branch which was based of the   v0.1.4 tag.

cc: @timkinnane

**Comment by geekgonecrazy** [comment]
Support for this was added in v0.1.4 and also present in v1.0.3.

Closing now.
