### ISSUE TITLE
Hubot doesn't talk

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/hubot-rocketchat#143]
So I've managed to get hubot to join my server with

docker run -it -e ROCKETCHAT_URL=local:3000 \
	-e ROCKETCHAT_ROOM=General \
	-e ROCKETCHAT_USER=Dicebot \
	-e ROCKETCHAT_PASSWORD=password \
	-e BOT_NAME=Dicebot \
	-e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help,hubot-roller \
	-v $PWD/scripts:/home/hubot/scripts \
	rocketchat/hubot-rocketchat

[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: Dicebot
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO Connecting To: localhost:3000
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO General
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO Logging In
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO Successfully Logged In
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO Looking up Room ID for: General
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO Joining Room: GENERAL
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO rid:  [ 'GENERAL' ]
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO All rooms joined.
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO Successfully joined room: GENERAL
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
[Sat Jul 02 2016 12:40:11 GMT+0000 (UTC)] INFO Subscribing to Room: __my_messages__

and it connects, i can see it in the GENERAL room.
However when I try hubot help, Dicebot help, or the roll commands nothing happens or gets printed in terminal.

**Comment by Sing-Li** [comment]
That is strange.  See "my_messages" - where would it get that from? It is not in your env vars.

**Comment by wargamesqcf** [comment]
That was a bad copy paste but in support chat you said to define adapter so i did and now it works.

  -e BOT_NAME=Dicebot \
    -e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help \
    -v $PWD/scripts:/home/hubot/scripts \
    rocketchat/hubot-rocketchat:v0.1.4
