### ISSUE TITLE
Hubot can't send messages with attachments.

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/hubot-rocketchat#146]
Related to #139, cc @geekgonecrazy, @ngenerio

Hey, I've been working on #139 with @ngenerio. His PR fixes receiving the attachment in the msg object, but I'm trying to then forward attachments sent to a bot in a new DM. It looks like the adaptor method `sendMessageByRoomId` only accepts raw text strings, not message objects.

I'm going to try and change that method to accept either an object or string. If you've got an idea how that should be handled, please speak up before I make a mess of it 😜

**Comment by Sing-Li** [comment]
Safe to modify.   `sendMessageByRoomId` is on the driver and (should) only internally used by us in one single flow.  Modifying it should have no major impact.   You can be super-safe by adding the object as a third optional argument 😀

**Comment by timkinnane** [comment]
Thanks @Sing-Li, good advice. Will follow up shortly.
