### ISSUE TITLE
bot is not connected

### ISSUE THREAD

**Issue by oinirio** [RocketChat/hubot-rocketchat#15]
When I the docker image the output is
```
[Tue Jun 09 2015 15:41:01 GMT+0000 (UTC)] INFO running rocketchat
[Tue Jun 09 2015 15:41:01 GMT+0000 (UTC)] INFO login
```

I try creating a user bot and rocketbot but is still not working

this are my configs
```
_meteorurl = "192.168.0.11:3000"
_hubotuser = "rocketbot"
_hubotpassword = "demodemo"
_roomid = "57om6EQCcFami9wuT"
```

to run the container I copy/paste the same command from inside the clones repo

**Comment by Sing-Li** [comment]
@oinirio    it seems you may not have access to that IP address from inside the running container.  

While container running and stuck at login, try:
```
docker exec -i -t  <container id>   bash
```
This will run a shell inside the container.  Then troubleshoot using ping.
You can get the running <container id> by:
```
docker ps
```

**Comment by oinirio** [comment]
@Sing-Li I'm running openSuse and the ping works from inside the container to my LAN by running 
```
docker inspect <container id>
```
I got the container internal IP and the ping works from localhost -> container

**Comment by Sing-Li** [comment]
@oinirio    Did "ping 192.168.0.11" worked from INSIDE the container (not using inspect) ?

Did you turn the default firewall off?

**Comment by oinirio** [comment]
@Sing-Li My bad was the firewall actually, it's working now
