### ISSUE TITLE
Why the git url for asteroid?

### ISSUE THREAD

**Issue by geekytime** [RocketChat/hubot-rocketchat#151]
Using git URLs breaks semver, and also causes problems for a lot of people using internal npm mirrors.

Is there some reason we can't pick a semver version of asteroid and go with it?

**Comment by geekgonecrazy** [comment]
Asteroid was undergoing a re-write with a lot of changes.. We had some changes we needed to add to it to allow custom login method so we pointed to our fork. 

We haven't had time to check out the new version of asteroid and see how the adapter behaves and potentially open a PR to get the fixes we need in.

So this is why..
