### ISSUE TITLE
Error Running Yo: npm ERR! not a package /tmp/npm-30929-OgybIFr-/github.com/RocketChat/asteroid.git

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/hubot-rocketchat#153]
When I run `yo hubot` as a non-root user, I am receiving the following error:

    [richlu@chat r2z2-test3]$ yo hubot
                         _____________________________
                        /                             \
       //\              |      Extracting input for    |
      ////\    _____    |   self-replication process   |
     //////\  /_____\   \                             /
     ======= |[^_/\_]|   /----------------------------
      |   | _|___@@__|__
      +===+/  ///     \_\
       | |_\ /// HUBOT/\\
       |___/\//      /  \\
             \      /   +---+
              \____/    |   |
               | //|    +===+
                \//      |xx|
    
    ? Owner r2z2
    ? Bot name r2z2.api
    ? Description A simple helpful robot for your Company
    ? Bot adapter (campfire) rocketchatgot back false
    ? Bot adapter rocketchat
       create bin/hubot
       create bin/hubot.cmd
       create Procfile
       create README.md
       create external-scripts.json
       create hubot-scripts.json
       create .gitignore
       create package.json
       create scripts/example.coffee
       create .editorconfig
                         _____________________________
     _____              /                             \
     \    \             |   Self-replication process   |
     |    |    _____    |          complete...         |
     |__\\|   /_____\   \     Good luck with that.    /
       |//+  |[^_/\_]|   /----------------------------
      |   | _|___@@__|__
      +===+/  ///     \_\
       | |_\ /// HUBOT/\\
       |___/\//      /  \\
             \      /   +---+
              \____/    |   |
               | //|    +===+
                \//      |xx|
    
    npm ERR! not a package /tmp/npm-30929-OgybIFr-/github.com/RocketChat/asteroid.git
    npm ERR! Error: ENOENT, open '/tmp/npm-30929-OgybIFr-/github.com/RocketChat/asteroid.git-unpack/package.json'
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/npm/npm/issues>
    
    npm ERR! System Linux 3.10.0-327.el7.x86_64
    npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-rocketchat" "--save"
    npm ERR! cwd /home/richlu/r2z2-test3
    npm ERR! node -v v0.10.40
    npm ERR! npm -v 1.4.28
    npm ERR! path /tmp/npm-30929-OgybIFr-/github.com/RocketChat/asteroid.git-unpack/package.json
    npm ERR! code ENOENT
    npm ERR! errno 34
    npm ERR! not ok code 0

My `package.json` turns out empty of dependencies. The last time I ran `yo hubot`, although a few months now, it was running fine. I had yo installed as root. When I try running yo hubot as root I receive:

    [root@chat hubot-test]# yo hubot

    Error: EACCES, permission denied '/root/.config'
        at Object.fs.mkdirSync (fs.js:654:18)
        at sync (/usr/local/lib/node_modules/yo/node_modules/mkdirp/index.js:71:13)
        at Function.sync (/usr/local/lib/node_modules/yo/node_modules/mkdirp/index.js:77:24)
        at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:38:13)
        at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
        at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
        at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:130:11)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)

The file `/root/.config` doesn't exist. I am not sure if this is a relevant issue. I'm just trying to dig deeper and determine where this issue is coming from and would like some help.

**Comment by richardwlu** [comment]
It looks like the `/tmp/npm-14425-3PWTo3x9/github.com/RocketChat/asteroid.git-unpack/package.json` doesn't exist. Anyone have any idea why this would be?

**Comment by mcmcghee** [comment]
Having the same issue. Installed RocketChat 0.37.1, installed hubot, and `ran npm install hubot-rocketchat`.

```
npm ERR! not a package /tmp/npm-1935-PYBoJJWE/github.com/RocketChat/asteroid.git
npm ERR! Error: ENOENT, open '/tmp/npm-1935-PYBoJJWE/github.com/RocketChat/asteroid.git-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hubot-rocketchat"
npm ERR! cwd /home/intsysadmin/myhubot
npm ERR! node -v v0.10.43
npm ERR! npm -v 1.4.29
npm ERR! path /tmp/npm-1935-PYBoJJWE/github.com/RocketChat/asteroid.git-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not ok code 0
```

**Comment by richardwlu** [comment]
@mcmcghee I did some testing and I am led to believe the issue is coming from an outdated version of npm or yo. There must be a directory structure change or something.

**Hubot generation failed with the following:**

- yo v1.5.0
- node v0.10.40
- npm v1.4.28

**Hubot generation successful with the following:**
- yo v1.8.4
- node v0.12.15
- npm v2.15.1

We're running fairly close versions of npm. What version of yo are you running? Try updating npm with `npm install -g npm`.

**Comment by mcmcghee** [comment]
@richardwlu Currently at:

- yo v1.8.4
- node v0.10.43
- npm v1.4.29

Will test upgrading NPM and report back

**Comment by geekgonecrazy** [comment]
We've had some people having issues with yoeman.  If you'll note in the README.  We have options for specifying all the options yo asks for at once.  We've had many have success with this route.

Though at this time you would need to edit the package.json after yo finished.. and modify the version of hubot-rocketchat to 0.1.4 then do an npm install before running hubot.

**Comment by richardwlu** [comment]
@geekgonecrazy Will hubot-rocketchat 0.1.4 work with RC >=0.36? I'm currently on 0.36 and could upgrade to 0.37.

**Comment by geekgonecrazy** [comment]
@richardwlu It should... but i've seen a few cases where people have said that it does not.  I'm investigating this today.  I have a freshly upgraded 0.37.0 instance i'm going to see if I can get hubot working with.

**Comment by richardwlu** [comment]
@geekgonecrazy Gotcha. We look forward to hear what you find. Thank you!

**Comment by mcmcghee** [comment]
Issued a `npm install -g npm` per @richardwlu suggestion (thanks!) and it upgraded npm to v3.10.6.

I was then able to execute `npm install hubot-rocketchat` without errors. Appears everything is working now.

**Comment by richardwlu** [comment]
@mcmcghee Good to hear! Is your hubot able to listen and respond to messages while on RC 0.37.1? I was looking to do a downgrade to 0.31 (our last working w/ bot) this evening so we can get our bot back up and working but if yours works while on hubot-rocketchat to 0.1.4 then I'll consider the upgrading RC to 0.37 then.

**Comment by richardwlu** [comment]
@geekgonecrazy @mcmcghee I stood up a test instance of RC 0.37.1 running Hubot with adapter 0.1.4 but was unable to successfully subscribe:

    r2z2-0 (out): 2016-08-18 19:42:55 407: [Thu Aug 18 2016 19:42:55 GMT+0000 (UTC)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found
    r2z2-0 (out): [Thu Aug 18 2016 19:42:55 GMT+0000 (UTC)] ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}
    r2z2-0 (out): [Thu Aug 18 2016 19:42:55 GMT+0000 (UTC)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.

Let me know if anyone else is receiving the same.

**Comment by jarbro** [comment]
I too upgraded my npm per @richardwlu suggestion and was able to install hubot-rocketchat w/o issue.

**Comment by geekgonecrazy** [comment]
@richardwlu please try adapter 1.0.1 I just tried locally and it seems to be working.

**Comment by richardwlu** [comment]
@geekgonecrazy RC 0.37.1 and Adapter 1.0.1 does work :)

**Comment by geekgonecrazy** [comment]
@richardwlu fantastic!  Thanks for reporting back.  I'm going to update documentation and cut a new release.  Hopefully we can put this problem behind us :grin:

**Comment by richardwlu** [comment]
@geekgonecrazy I hope so! Just FYI, some users still report that Adapter 1.0.1 isn't working for them over at #142.

**Comment by richardwlu** [comment]
I'm going to go ahead and close this issue since this is for for running into the ENOENT Error when running yo. Solution is to upgrade npm via `npm install -g npm`.

**Comment by geekgonecrazy** [comment]
@richardwlu 👍 thanks for the feedback
