### ISSUE TITLE
Npm update

### ISSUE THREAD

**Issue by chispaa** [RocketChat/hubot-rocketchat#156]
Hi,

Sorry for the newbie question but I'm running hubot via npm and I would like to update to the latest version to fix the authentication issue.

To update rocketchat I move the old folder and reinstall, but with hubot I don't want to remove the hubot scripts.

Thanks!.

**Comment by geekgonecrazy** [comment]
@chispaa you should be able to do `npm outdated` and see something like this:

![image](https://cloud.githubusercontent.com/assets/51996/17903295/9fd418a6-6930-11e6-84a1-9110d89179c0.png)

You can either edit your bots package.json file and update the version number there... or you can run:

```
npm install hubot-rocketchat@1.0.3 --save
```

**Comment by chispaa** [comment]
I changed the package.json file and tried to update but it didn't work (mainly I didn't know what I was doing).

On the other hand, that command worked great and now I'm running the latest version, thanks!.

**Comment by geekgonecrazy** [comment]
Good to hear!
