### ISSUE TITLE
Bot no longer responds to commands given in a DM to the bot

### ISSUE THREAD

**Issue by cbrummitt** [RocketChat/hubot-rocketchat#157]
My bot no longer responds to commands given in a direct message to the bot. It is successfully responding to commands given in public channels (and I have `LISTEN_ON_ALL_PUBLIC` set to `true`). 

This problem started occurring after upgrading Rocket.Chat to 0.37 (from 0.35 or 0.36) and the Rocket-Hubot adapter from 0.1.4 to 1.0.3).

Is anyone else having this problem?

**Comment by geekgonecrazy** [comment]
@cbrummitt try adding this environment variable:
```
RESPOND_TO_DM=true
```

We might should think about defaulting this to true...

**Comment by cbrummitt** [comment]
Thank you @geekgonecrazy this fixed it!
