### ISSUE TITLE
Alias `/` is now overridden by rocketbot

### ISSUE THREAD

**Issue by cbrummitt** [RocketChat/hubot-rocketchat#158]
I had been using `/` as an alias for my bot's name (i.e., `HUBOT_ALIAS` is set to `/`). After upgrading the Rocket-Hubot adapter to `v1.0.3`, whenever I begin a command with the alias `/` (instead of the bot's name) I get a response from `@rocketbot` saying 

> No such command: `/<command-name>`

Is there a way to override the rocketbot so that I can continue using the alias `/`? Or do I need to pick a new alias?

**Comment by geekgonecrazy** [comment]
@cbrummitt wow... i'm actually really shocked that one ever worked.   From my understanding we grab the `/` in rocket.chat and intercept it before its ever even sent.

**Comment by cbrummitt** [comment]
@geekgonecrazy implemented a fix in version `0.40.0` of Rocket.Chat: there's now a boolean setting "Allow Unrecognized Slash Commands" in the administrator's "Message" settings. Setting this setting to `True` allows Hubot to use `/` as an alias. Thanks @geekgonecrazy !
