### ISSUE TITLE
How to autostart docker-compose rocketchat after reboot?

### ISSUE THREAD

**Issue by Hostile** [RocketChat/hubot-rocketchat#165]
Hi, so managed to install rocketchat + hubot and looks like its working okay.

I start it with command docker-compose up -d hubot

How can I add this to start at boot after server restart?

Ubuntu 16.04

Thanks

**Comment by Hostile** [comment]
it starts with @reboot crontab job

**Comment by geekgonecrazy** [comment]
You should be able to add: `restart: always` to the hubot section of the docker-compose.

**Comment by Hostile** [comment]
it did not come up after reboot

`hubot:
  image: rocketchat/hubot-rocketchat:v1.0.3
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_ROOM=
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=xxxx
    - BOT_NAME=bot
    - RESPOND_TO_EDITED=true
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics,hubot                                                                              -pugme,hubot-whois,hubot-reddit,hubot-praise,hubot-urban-dictionary,hubot-bible-                                                                              api,hubot-hackernews,hubot-cron-checker,hubot-cron-checker,hubot-steamdailydeal,                                                                              hubot-drupal,hubot-reminder-bot,hubot-giphy-gifme,hubot-pokemon,hubot-http-code,                                                                              hubot-digweb
  links:
    - rocketchat:rocketchat
  ports:
    - 3001:8080
  restart: always`

**Comment by Hostile** [comment]
> hubot:
  image: rocketchat/hubot-rocketchat:v1.0.3
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_ROOM=
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=bot3110
    - BOT_NAME=bot
    - RESPOND_TO_EDITED=true
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics,hubot                                                                              -pugme,hubot-whois,hubot-reddit,hubot-praise,hubot-urban-dictionary,hubot-bible-                                                                              api,hubot-hackernews,hubot-cron-checker,hubot-cron-checker,hubot-steamdailydeal,                                                                              hubot-drupal,hubot-reminder-bot,hubot-giphy-gifme,hubot-pokemon,hubot-http-code,                                                                              hubot-digweb
  links:
    - rocketchat:rocketchat
  ports:
    - 3001:8080
  restart: always

**Comment by wandonye** [comment]
I have the same problem here.

**Comment by gasparch** [comment]
`restart: always` only affects how Docker will restart containers after their crash :)

**Comment by geekgonecrazy** [comment]
going to go ahead and close this.  This isn't a hubot specific question.  I'd look around the internet for how others are starting docker-compose on restart.  Those solutions should work here.

I'm guessing could use a systemd service or something of that nature.
