### ISSUE TITLE
Email Configuration / smtp configuration issues

### ISSUE THREAD

**Issue by Hostile** [RocketChat/hubot-rocketchat#166]
is there anywhere better guide then https://rocket.chat/docs/administrator-guides/email/ ?

I tried but no succes

What mail transport agent is recomended? postfix ? or exim4 will do?

exim looks easier to configure smtp tho

Im on Ubuntu 16.04

It simes complicated setting smtp

Thanks

**Comment by Hostile** [comment]
using google smtp works for me

**Comment by geekgonecrazy** [comment]
Please open issues on the correct repo. RocketChat/Rocket.Chat is the repo you should post this question.
