### ISSUE TITLE
Getting verbose output

### ISSUE THREAD

**Issue by digininja** [RocketChat/hubot-rocketchat#167]
I've got the bot running  through Docker as suggested in the Readme, it connected to RocketChat once but didn't respond to any requests and after a restart it doesn't seem to be connecting.

How can I get the Docker image to push out verbose information so I can see what is going on?

**Comment by Sing-Li** [comment]
`docker logs <container id or name>`    The log is quite verbose.

**Comment by digininja** [comment]
This is all I get which matches the output I get when I start the container:

```
[root@localhost ~]# docker logs f00bf05aa874
hubot-help@0.2.0 node_modules/hubot-help

hubot-pugme@0.1.0 node_modules/hubot-pugme
[Mon Sep 19 2016 04:49:14 GMT+0000 (UTC)] INFO Starting Rocketchat adapter version 1.0.4...
[Mon Sep 19 2016 04:49:14 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: HackBot
[Mon Sep 19 2016 04:49:14 GMT+0000 (UTC)] INFO I will also respond to my Rocket.Chat username as an alias: bot
[Mon Sep 19 2016 04:49:14 GMT+0000 (UTC)] WARNING No services ROCKETCHAT_ROOM provided to Hubot, using
[Mon Sep 19 2016 04:49:14 GMT+0000 (UTC)] INFO Connecting To: localhost:3000
````
I assume that it isn't managing to connect but can't work out why.

The login credentials are correct, I've checked those by logging in to the web interface. RocketChat is running and I'm logged in as different user through a browser so that is OK. What else can I try?

**Comment by geekgonecrazy** [comment]
@digininja when starting up the container are you specifying a ROCKETCHAT_URL? If so make sure to use a dns resolvable hostname, or an ip.  localhost is not resolvable to the underlying host, but pointing to the actual container its self.

**Comment by digininja** [comment]
Of course, that will be it. Wondering how it managed to join the channel
once though, unless that was automatic when I set the account up and I
didn't notice.

Now to work out what IPs are going where so I can pick the right IP to use.
Thanks

**Comment by geekgonecrazy** [comment]
Alternatively.. If you are running Rocket.Chat its self also in a container, you can link it to this container by adding `--link <rocketchat container here>:rocketchat`  and in your ROCKETCHAT_URL use rocketchat:3000

Yes likely joined the channel when you set the account up.  Any new user joins General by default out of the box.

If it doesn't get past the connecting it isn't connecting.  I'm still hunting to get more verbose logging from the underlying library.  I hate that it doesn't log when its failing to connect.  Makes it hard to troubleshoot.

**Comment by digininja** [comment]
I've got RocketChat installed locally but sounds like it would be easier to
go with Docker for it so I'll investigate that.

**Comment by digininja** [comment]
Got it all working, thanks. Not 100% sure what is going on, got a long way
to go in learning Docker.

**Comment by geekgonecrazy** [comment]
Let us know if you need any help!  👍
