### ISSUE TITLE
first scripts

### ISSUE THREAD

**Issue by digininja** [RocketChat/hubot-rocketchat#169]
I've got my bot working in Docker and the default pug script is running fine so now I'm on to writing my own scripts. I've taken the example.coffee from ~/scripts , copied it to its own file and uncommented a few of the examples. After some messing with docker I managed to get an image created that contained my new file but after starting it the new script was ignored. Do I need to do something special to get scripts from the scripts directory working or should they just be picked up when the bot starts?

Is there an easy way to have the bot pick up the changes on the fly so I can do quick debugging?

Finally, is there a better place to ask questions like this? Some people don't like using issues to ask questions.

**Comment by digininja** [comment]
Got it all working, amazing what an hour on a train with no interruptions can do.

**Comment by geekgonecrazy** [comment]
@digininja great!  Sorry about the delayed response.  Yeah developing scripts in docker isn't ideal.  I've been debating how to maybe do an image that can auto reload based on script changes just for development.

**Comment by digininja** [comment]
No problem, you aren't getting paid for support.

An auto reload or forced reload would be really useful.

**Comment by geekgonecrazy** [comment]
If you need more real time help in the future we usually are in [#hubot](https://demo.rocket.chat/channel/hubot)

**Comment by digininja** [comment]
Ok thanks. Got a big plan that involves all this, just need time to do it.
I can see all the bits I need though so it will definitely work.
