### ISSUE TITLE
Send attachments

### ISSUE THREAD

**Issue by Huljo** [RocketChat/hubot-rocketchat#172]
Hi, 

Is there any way to send an attachment to a channel/DM ?

That should be a great thing to send some media content.

**Comment by geekgonecrazy** [comment]
@Huljo there absolutely is a way to do that.  just add an attachment object on the message object.  

So something like 
```
msg.attachments = [
    {
      title: "text",
      title_link: "https://link",
      text: "Rocket.Chat, the best open source chat",
      image_url: "https://rocket.chat/images/mockup.png",
      color: "#764FA5"
    }
];
```

Other properties available like:
* title_link_download: true
* image_url 
* image_type
* image_size
* image_dimensions
* audio_url
* audio_type
* audio_size
* video_url
* video_type
video_size

**Comment by Huljo** [comment]
Thank you @geekgonecrazy, I'll have a try.

**Comment by lukasi** [comment]
@geekgonecrazy hello, could you please explain where I should add message object

**Comment by fedevegili** [comment]
for future googlers, here is an example:

`module.exports = function(robot) {
	var msg = {};

	msg.attachments = [
		{
			title: "text",
			title_link: "https://link",
			text: "Rocket.Chat, the best open source chat",
			image_url: "https://rocket.chat/images/mockup.png",
			color: "#764FA5"
		}
	];

	robot.messageRoom("general", msg);
};`

**Comment by Fabianski-tr** [comment]
@fedevegili do you have a script example (js or coffescript)? I try to integrate with my examples but the hubot container return error and not stop it.

Thank you!

**Comment by abhiram-patientrials** [comment]
Can we open these links in the hubot like webview rather than opening in next tab or browser?
