### ISSUE TITLE
Hubot Help doesn't reply in private

### ISSUE THREAD

**Issue by rogerpfaff** [RocketChat/hubot-rocketchat#174]
While researching this problem https://github.com/hubot-scripts/hubot-help/issues/15 I digged into all scripts involved and found this issue https://github.com/RocketChat/hubot-rocketchat/issues/161 very well hinting to a connection between both.

Something is not working well together between the help script and the rocketchat adapter. The help script sends a message to a user name https://github.com/hubot-scripts/hubot-help/blob/master/src/help.coffee#L76 which is handled by the adapter here https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat.coffee#L196

This again is handled in the driver on this line https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat_driver.coffee#L74

So implementing the sendDirect messages in the rocketchat adapter https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat.coffee#L202 is a very nice idea but it seems to be good for developing something against the adapter by using this method but it seems to be not the original way(TM) it was meant to be.

I also guess we will not get the maintainers of modules to rewrite code specifically for the rocketchat adapter. They just send a reply to the channel or a message to the user.

Maybe I did not understand something on the way and I would appreciate any clarification on this issue.

**Comment by timkinnane** [comment]
Closing because there's no clear action to take here.
