### ISSUE TITLE
Hubot does not respond (installed using docker-compose)

### ISSUE THREAD

**Issue by lukaszwos** [RocketChat/hubot-rocketchat#175]
I installed rocket.chat and hubot on a digital ocean droplet  using docker-compose. 
Right now Rocket.chat is up, hubot is connected (bot user is green in rocket.chat) but it does not respond.

Here is my docker-compose.yml:
https://gist.github.com/lukaszwos/980d1e0b8f791362e28c4eb5a731d9ef

This is my first deployment using docker and while it is fast and easy to do, I don't even know where are those apps (hubot and rocket) installed, so troubleshooting is hard for me in this case.

Thanks in advance for any help

**Comment by lukaszwos** [comment]
OK. hubot is up. I had to change:
   

image: rocketchat/hubot-rocketchat:v0.1.4

 
to:

image: rocketchat/hubot-rocketchat:latest in hubot part of .yml

s a problem when rocketchat imagee _rocketchat image_and _hubot image_ are different (DUH...)

But still how do I service hubot started with docker-compose? For instance. Where (folder location), should I run npm install [script name] to add it to hubot? The same folder in which .yml file is located?

How can I customise scripts? Where are they located?

**Comment by geekgonecrazy** [comment]
The issue here is you were pointing at v0.1.4 and latest needed is v1.0.4 at least.  Where did you find this docker-compose file?

**Comment by lukaszwos** [comment]
Yeah. That's exactly what I wrote above.  I didn't find this yml file anywhere.  I wrote it myself basing on info I gathered. 

Anyway. Thanks for taking interest in this issue. 

Hubot is awesome.
