### ISSUE TITLE
How to send a private message to a user

### ISSUE THREAD

**Issue by kevinkuszyk** [RocketChat/hubot-rocketchat#176]
I'm trying to send a private message to a user when a web hook notification is received.  My code looks like this:

``` coffee
robot.send user, message
```

This works, but the message always comes to the room the user is currently in.  I was expecting it to come through as a private message between the user and Hubot.  Is there a way to send a private message to a user?

I've read through #136 - I'm not sure if that issue is related to my use case.

**Comment by geekgonecrazy** [comment]
The key to this one lies in this comment here: https://github.com/RocketChat/hubot-rocketchat/issues/136#issuecomment-227949522

In Rocket.Chat even a direct message is considered a room.  So you need to do something like:

> So you can find the DM id for hubot to address a user, with DM = robot.adapter.chatdriver.getDirectMessageRoomId user.name

> Then you can send to that room with robot.adapter.chatdriver.sendMessageByRoomId msg.text, DM.room

**Comment by kevinkuszyk** [comment]
@geekgonecrazy thanks for the tip.  After re-reading that issue and digging through the code I came across the `sendDirect` method.  I now have this working in my script:

```
robot.adapter.sendDirect { user }, message
```

Obviously this will only work with the Rocket.Chat adapter.  Are you aware of any conventions for sending direct messages in scripts that will work across adapters?

**Comment by geekgonecrazy** [comment]
i'm not aware of any conventions, though we typically try and use commands we see in other adapters, while not limiting our selves if no one else has it.

**Comment by kevinkuszyk** [comment]
Thanks @geekgonecrazy, I'll open an issue in the Hubot repro to see if they have any best practice.  

I'm building a script which I want to open source, so I don't want to take any Rocket.Chat dependencies.  Maybe it's something they can add to the adapter interface in v3.

**Comment by geekgonecrazy** [comment]
Based on the response there it looks like messageRoom might be a method we should implement?

**Comment by kevinkuszyk** [comment]
@geekgonecrazy it looks that way, but it might not be a straight forward fix.  

You'd need some way to to know if the room is a channel or a private room (i.e. a DM to the user).  If it's channel then the existing method works fine.  If it's a DM then you'd need to call out to `sendDirect`.

It's unlikely I'll have a stab at fixing this now, as we've changed our design to send team city notifications to a channel instead of a private message to the user.

**Comment by geekgonecrazy** [comment]
As far as Rocket.Chat or the adapter is concerned though A DM / Private Group / Channel are all rooms.  It has some meta data, but they are all just rooms.

So something to keep in mind.

**Comment by timkinnane** [comment]
See #136 for similar scenario and solution.
