### ISSUE TITLE
hubot rocket.chat adapter install permission problem

### ISSUE THREAD

**Issue by jy2008** [RocketChat/hubot-rocketchat#179]
When i get to the step of ```sudo yo hubot --owner="OWNER <owner@example.com>" --name="bot" --description="Bot" --adapter="rocketchat@0.1"``` , PuTTY gave me error saying i don't have permission to some npm file, I researched online, looks like it is a common problem. So i used https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory 
Option 1 to change the permission

and this is what i got from PuTTY, I get the feel this is the right direction, but detail is wrong, can anyone tell me what went wrong?
```
jy@ubuntu-1gb-sfo2-01:~$ npm config get prefix
/usr/local
jy@ubuntu-1gb-sfo2-01:~$ sudo chown -R $jy /usr/local/lib/node_modules/
[sudo] password for jy:
chown: missing operand after ‘/usr/local/lib/node_modules/’
Try 'chown --help' for more information.
```

**Comment by geekgonecrazy** [comment]
this isn't really an issue with our adapter...

But in your command you're missing the use to assign ownership too.  Ex: 
`sudo chown -R bob $jy /usr/local/lib/node_modules/`

Read more about chown and how to use it here: http://www.computerhope.com/unix/uchown.htm
