### ISSUE TITLE
Can't get room name in my message handler

### ISSUE THREAD

**Issue by greyarch** [RocketChat/hubot-rocketchat#180]
In the following custom script:

```
module.exports = (robot) ->
   robot.respond /ping/i, (res) ->
     console.log res.message.room
     res.reply 'pong'
```

The **res.message.room** is an ID (mongo document Id?) and not the room name, as the hubot docs suggest it should be. Is this a bug or the room name is available via other means?

**Comment by geekgonecrazy** [comment]
Are you needing the room name for some sort of logic?  Otherwise this is perfectly normal.  The roomid is what is used in every case through out the bot to send messages to a room.

**Comment by JigSawFr** [comment]
For example if you need to send room name to an API or anything else.
In my case, I need to user room name for a welcome message.
And later to liste some rooms.
I have IDs but i can't call a method to reverse them to their name. It's strange.

And also msg contain 2 references to room with:
- msg.message.room
- msg.message.user.room

It could be great to add room name too with ID or a method to get room name by ID.
Thanks you

**Comment by timkinnane** [comment]
Fixed in develop branch, pending release.
