### ISSUE TITLE
PM2 command not found on hubot rc adapter

### ISSUE THREAD

**Issue by jy2008** [RocketChat/hubot-rocketchat#181]
I am installing PM2 for hubot rocket.chat adapter. so i did the following:
I firstly added a <pm2.json> file to hubot adapter folder, then 
`sudo npm install pm2 -g`
`cd <hubot directory>`
`pm2 start <pm2.json>`

The i got error saying this:
```
No command 'pm2' found, did you mean:
 Command 'wm2' from package 'wm2' (universe)
 Command 'pms' from package 'pms' (universe)
 Command 'pmk' from package 'pmk' (universe)
 Command 'pmw' from package 'pmw' (universe)
 Command 'fpm2' from package 'fpm2' (universe)
 Command 'pom2' from package 'libpod-pom-perl' (universe)
 Command 'pmi' from package 'powermanagement-interface' (universe)
 Command 'pm' from package 'powerman' (universe)
pm2: command not found
```
Then I tried to add the path by doing: 
`sudo env PATH=$PATH:/home/jy/.npm-global/bin pm2 startup -u safeuser`
and
`export PATH=$PATH:/home/jy/.npm-global/bin`
and restarted PuTTY,

still get the same error.

when I went to where PM2 is at, which is /home/jy/.npm-global/bin, and do `pm2 start <pm2.json>` command, still get the same error.

Is there anything i did wrong? or there might be other reasons?

**Comment by geekgonecrazy** [comment]
pm2 isn't needed by hubot.  Please open an issue on the pm2 repo for help with pm2
