### ISSUE TITLE
hubot not responding to redis

### ISSUE THREAD

**Issue by jy2008** [RocketChat/hubot-rocketchat#182]
my hubot rocket.chat adapter works well except for every time i started hubot, I had to reset the following items:
```
export ROCKETCHAT_USER=bot
export ROCKETCHAT_PASSWORD=bot
export ROCKETCHAT_AUTH=password
export HUBOT_YOUTUBE_API_KEY=<your token>
```
I get the feel hubot is not really responding to redis that i installed. I do have `hubot-redis-brain` installed as well. Is there any other setting I need to do in order to make it work? Or should i just re-install the whole thing? what might be the possible reason?

**Comment by geekgonecrazy** [comment]
Redis isn't going to magically remember things.  You have to explicitely save them there.

Also.. Those are environment variables needed by hubot.  These are needed by the hubot adapter before it ever even gets to the point of connecting to the redis brain.

**Comment by jy2008** [comment]
thanks, all i did is installed redis and hubot-redis-brain, nothing else. i didn't setup or add anything to environment. Unfortunately i am out of clue here, how to do and what to do? is there tutorial you know that can help me? or i need to ask hubot github community?

**Comment by geekgonecrazy** [comment]
@jy2008 let me break it up in two parts.

```
export ROCKETCHAT_USER=bot
export ROCKETCHAT_PASSWORD=bot
export ROCKETCHAT_AUTH=password
export HUBOT_YOUTUBE_API_KEY=<your token>
```

These are environment variables... you have to set them every time.

My suggestion is to create a file called `start` with these contents:
```
#!/bin/bash

export ROCKETCHAT_USER=bot
export ROCKETCHAT_PASSWORD=bot
export ROCKETCHAT_AUTH=password
export HUBOT_YOUTUBE_API_KEY=<your token>

bin/hubot -a rocketchat
```
then do: `chmod +x start` and then you run your bot by just doing: `./start`

As far as using the brain.  Please look at the hubot brain documentation.  To store something in the brain you will have to actually save it to the brain.

**Comment by jy2008** [comment]
thank you very much, that is crystal clear! :)
