### ISSUE TITLE
hubot rocket.chat adapter cannot be restarted without re-configuration

### ISSUE THREAD

**Issue by jy2008** [RocketChat/hubot-rocketchat#183]
Every time when i started hubot, i have to do the following first before `bin/hubot -a rocketchat`? Why is that?
```
export ROCKETCHAT_USER=bot
export ROCKETCHAT_PASSWORD=bot
export ROCKETCHAT_AUTH=password
```
Also I did install `redis` and `hubot-redis-brain`, and from the following info i got when i log in hubot, the adapter did connect to redis:
```
[Wed Oct 19 2016 02:44:24 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Wed Oct 19 2016 02:44:24 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis

```

**Comment by geekgonecrazy** [comment]
Please see answer already given here: https://github.com/RocketChat/hubot-rocketchat/issues/182#issuecomment-254556722
