### ISSUE TITLE
Bluebird module fails to load and rocketchat_hubot_1 exited with code 1

### ISSUE THREAD

**Issue by pasmon** [RocketChat/hubot-rocketchat#186]
We are using bunch of modules with our Hubot (using docker-compose.yml), but Bluebird causes Hubot to "crash":

> hubot_1       | Your hubot-scripts.json is empty, so you just need to remove it.
> hubot_1       | Jenkins Notifier Hubot script started. Awaiting requests.
> hubot_1       | [Tue Oct 25 2016 10:04:49 GMT+0000 (UTC)] ERROR Error loading scripts from npm package - TypeError: Cannot set property '_bitField' of undefined
> hubot_1       |   at Promise (/home/hubot/node_modules/bluebird/js/release/promise.js:70:20)
> hubot_1       |   at Robot.loadExternalScripts (/home/hubot/node_modules/hubot/src/robot.coffee:401:11, <js>:272:39)
> hubot_1       |   at /home/hubot/node_modules/hubot/bin/hubot:152:11, <js>:159:26
> hubot_1       |   at fs.js:334:14
> hubot_1       |   at FSReqWrap.oncomplete (fs.js:95:15)
> hubot_1       |
> rocketchat_hubot_1 exited with code 1

This is the list of external scripts we would like to use with our Hubot container:
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings,hubot-proxy-loader,hubot-gitsy,hubot-gitlab-hooks,hubot-darksky,hubot-gocd,hubot-voting,hubot-jenkins-notifier,hubot-lunch-at-amica,hubot-jira-linkifier,hubot-daily-comic,bluebird,hubot-scripts-stock,hubot-rolldice,hubot-decides,hubot-wikipedia,hubot-calculator

We need Bluebird for some of our own scripts which we are not using as NPMs. Any ideas how to get Bluebird working?

**Comment by timkinnane** [comment]
Develop branch is now fully async and dropped Bluebird. Soon to be released.
