### ISSUE TITLE
Error when email account is unverified

### ISSUE THREAD

**Issue by slasheks** [RocketChat/hubot-rocketchat#187]
When the email account of the registered bot is unverified, I receive the following error. This prevents the account from logging in via the bot but ok when trying via web browser. 

>```
>[Thu Nov 24 2016 03:53:35 GMT+0000 (UTC)] INFO Successfully connected!
>[Thu Nov 24 2016 03:53:35 GMT+0000 (UTC)] INFO 
>[Thu Nov 24 2016 03:53:35 GMT+0000 (UTC)] INFO Logging In
>[Thu Nov 24 2016 03:53:36 GMT+0000 (UTC)] ERROR Unable to Login: {"error":"error-invalid-email","reason":"Invalid email __email__","message":"Invalid email __email__ [error-invalid-email]","errorType":"Meteor.Error"} Reason: Invalid email __email__
>[Thu Nov 24 2016 03:53:36 GMT+0000 (UTC)] ERROR If joining GENERAL please make sure its using all caps.
>[Thu Nov 24 2016 03:53:36 GMT+0000 (UTC)] ERROR If using LDAP, turn off LDAP, and turn on general user registration with email verification off.
>[Thu Nov 24 2016 03:53:36 GMT+0000 (UTC)] ERROR {"error":"error-invalid-email","reason":"Invalid email __email__","message":"Invalid email __email__ [error-invalid-email]","errorType":"Meteor.Error"}
>[Thu Nov 24 2016 03:53:36 GMT+0000 (UTC)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.
>```

**Comment by geekgonecrazy** [comment]
@slasheks never encountered this.  Very curious that it allows you to login via UI but not the bot.

**Comment by timkinnane** [comment]
Not sure if this is persistent, but anyone encountering it should report an issue to the Rocket.Chat repo, because the adapter cannot resolve this by itself.

**Comment by online0227** [comment]
i encountered this but it happens only when making a new account via mobile app (latest android rocket chat app on google play)
