### ISSUE TITLE
Hubot doesn't reply in private chat to itself

### ISSUE THREAD

**Issue by kevinkuszyk** [RocketChat/hubot-rocketchat#189]
My bot is set to listen to all channels, and it's replying in public channels, but it's not responding to private messages to itself:

![image](https://cloud.githubusercontent.com/assets/2734580/20844123/47cb4f96-b8b6-11e6-8b17-1e29e5ff2a5a.png)

My config looks like this:

```
...
SET ROCKETCHAT_ROOM=''
SET ROCKETCHAT_USER=hubot
SET LISTEN_ON_ALL_PUBLIC=true
...
```

If I have some time next week, I'll dig into the code to see where it's going wrong.  In the meantime have I missed anything on the config?

**Comment by geekgonecrazy** [comment]
Can you give: RESPOND_TO_DM=true a try?

**Comment by kevinkuszyk** [comment]
Thanks @geekgonecrazy that's fixed it.  I'm not sure if there's a bug here, or if the readme needs updating:

> if 'true' then bot will listen and respond to direct messages. When setting the option to 'true', be sure to also set ROCKETCHAT_ROOM. This option needs not be set if you are including LISTEN_ON_ALL_PUBLIC. Default is 'false'.

**Comment by geekgonecrazy** [comment]
@kevinkusyk this is listed as an option in the readme.
