### ISSUE TITLE
How do I have a bot respond to messages in a LiveChat channel?

### ISSUE THREAD

**Issue by devinakumar** [RocketChat/hubot-rocketchat#195]
I want my bot to be able to respond to a query in a live chat channel and extract data from the conversation, so I tried calling the bot by name in the live chat channel.  I can see in the console that the bot knows it is being called by a certain room, but it is unable to respond.  How can I get the bot into the live chat conversation?  It keeps getting stuck after the TryCache method in the rocketchat driver.
<img width="567" alt="screen shot 2017-01-24 at 11 39 28 am" src="https://cloud.githubusercontent.com/assets/20134590/22263589/cffda282-e229-11e6-964e-9684c9011e3e.png">

**Comment by JigSawFr** [comment]
Same question

**Comment by gugahoa** [comment]
- Add bot as the only agent
- Send message via livechat once so the bot can enter the room
- Send the following messages mentioning it. Ex: `hubot ping`

**Comment by valeriucraciun** [comment]
I have  the same problem.
I have set up hubot as the only livechat-agent
when I send the mesage from chat I have this in logs:
![image](https://user-images.githubusercontent.com/1898515/31049970-bc41c0ba-a647-11e7-81ac-accc15392b53.png)
when I send the message from livechat only this line appears to log:
![image](https://user-images.githubusercontent.com/1898515/31049978-db242b30-a647-11e7-9cbb-6bd9a6ed559e.png)
My hubot logic is on a catch all block:
![image](https://user-images.githubusercontent.com/1898515/31049989-00e0925a-a648-11e7-986f-45ef092d37af.png)

Can you tell me if there are any 'tricks' in setting up hubot rocketchat adapter or rocketchat server?
Does anyone succeded on having hubot answering to the livechat?

I mention that I don't use the internal rocketchat hubot, but I use the hubot-rocketchat docker image

**Comment by valeriucraciun** [comment]
Hi again,

I managed to solve the issue.
I dig into your code and you have this:
RespondToLivechatMessage = (process.env.RESPOND_TO_LIVECHAT or "false").toLowerCase() is "true"

but RESPOND_TO_LIVECHAT is not documented on your page as being an environment variable.
Please update the documentation.

Regards,
Vali

**Comment by ruslantagirov** [comment]
Hi. I have set Rocket chat and Hubot, added hubot as only agent for Livechat, but Livechat doesn't see the agent online and doesn't allow user to start Livechcat conversation.
If I add a 'real' user to livechat agents, the Livechat works as expected, but without Hubot.
Hubot running as external service and has its own username in Rocket chat.
It does respond to direct messages (like 'help') and in #General channel (like 'test').
 
here are environment variables:
```
docker exec -it hubot-rocketchat printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=cbad60eb2288
TERM=xterm
RESPOND_TO_DM=true
LISTEN_ON_ALL_PUBLIC=true
ROCKETCHAT_ROOM=''
EXTERNAL_SCRIPTS=""
ROCKETCHAT_URL=mychathost:3000
BOT_NAME=my.bot
RESPOND_TO_LIVECHAT=true
ROCKETCHAT_USER=my.bot
HUBOT_LOG_LEVEL=debug
ROCKETCHAT_PASSWORD=my.bot
NPM_CONFIG_LOGLEVEL=info
NODE_VERSION=4.8.3
YARN_VERSION=0.24.4
BOT_OWNER=No owner specified
BOT_DESC=Hubot with rocketbot adapter
HOME=/home/hubot
```

**Comment by ruslantagirov** [comment]
I can't log Livechat messages because the 'client' side of chat says it's offline, so I can't even send a livechat message from a website.
I've added Hubot both as livechat-manager and livechat-user, but it seems it doesn't work.
I think that Hubot doesn't register itself as livechat-agent.

**Comment by ruslantagirov** [comment]
Finally got Hubot responding, but with strange settings.
1) I've set both human and hubot both as livechat agents and managers
2) I've set Livechat Routing Method = Guest Pool

Then I've finally got Livechat working on client side and sent message. Hubot brain now receives livechat messages, but it responds only to standard messages like 'help', 'ping', etc.  But it doesn't respond to 'custom' messages like 'test' in Livechat.
It does not respond to these kind of messages in DM as well. I think it's the root cause of not responding in Livechat.

It DOES respont to message 'test' in #general (reply was: "Test? TESTING? WE DON'T NEED NO TEST, EVERYTHING WORKS!", as expected).
See logs.

Livechat test:
```
[Fri Nov 09 2018 06:16:01 GMT+0000 (UTC)] INFO Message received with ID id
[Fri Nov 09 2018 06:16:01 GMT+0000 (UTC)] INFO Message receive callback id byvgPzm3GW9zqtHie ts Fri Nov 09 2018 06:16:01 GMT+0000 (UTC)
[Fri Nov 09 2018 06:16:01 GMT+0000 (UTC)] INFO [Incoming] guest-3: test
[Fri Nov 09 2018 06:16:01 GMT+0000 (UTC)] INFO Message sent to hubot brain.
[Fri Nov 09 2018 06:16:01 GMT+0000 (UTC)] DEBUG No listeners executed; falling back to catch-all

[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] INFO Message received with ID id
[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] INFO Message receive callback id aJJKa5SSTG7wBE83A ts Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)
[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] INFO [Incoming] guest-3: ping
[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] INFO Message sent to hubot brain.
[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] DEBUG Message 'my.bot ping' matched regex //^\s*[@]?(?:my.\.bot[:,]?|![:,]?)\s*(?:PING$)/i/; listener.options = { id: null }
[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'my..bot ping'
[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] INFO Sending Message To Room: wEj4hKcP3BaAqJMK6
[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] DEBUG Found cached Room ID for wEj4hKcP3BaAqJMK6: wEj4hKcP3BaAqJMK6
[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] DEBUG Preparing message from string
[Fri Nov 09 2018 06:16:06 GMT+0000 (UTC)] INFO Message received with ID id
```
#general channel test log:
```
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] INFO Message received with ID id
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] INFO Message receive callback id rsB3P9W7RPwziiQfC ts Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] INFO [Incoming] admin: test
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] INFO Looking up Room Name for: GENERAL
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] INFO setting roomName: general
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] INFO Message sent to hubot brain.
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] DEBUG Message 'test' matched regex //^test$/i/; listener.options = { id: null }
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'test'
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] INFO Sending Message To Room: general
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] INFO Looking up Room ID for: general
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] DEBUG Preparing message from string
[Fri Nov 09 2018 06:20:31 GMT+0000 (UTC)] INFO Message received with ID id
```
DM test log:
```
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] INFO Message received with ID id
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] INFO Message receive callback id 3xeDFvcaAxMnf2s6j ts Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] INFO [Incoming] admin: ping
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] INFO Message sent to hubot brain.
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] DEBUG Message 'my.bot ping' matched regex //^\s*[@]?(?:my\.bot[:,]?|![:,]?)\s*(?:PING$)/i/; listener.options = { id: null }
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'my.bot ping'
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] INFO Sending Message To Room: fEpvDSrCcpfZFMFDAuRKWDTjiY2FtcjZNe
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] INFO Looking up Room ID for: fEpvDSrCcpfZFMFDAuRKWDTjiY2FtcjZNe
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] DEBUG Preparing message from string
[Fri Nov 09 2018 06:28:36 GMT+0000 (UTC)] INFO Message received with ID id

[Fri Nov 09 2018 06:28:40 GMT+0000 (UTC)] INFO Message received with ID id
[Fri Nov 09 2018 06:28:40 GMT+0000 (UTC)] INFO Message receive callback id kAS3Twne7aoyAhmzJ ts Fri Nov 09 2018 06:28:40 GMT+0000 (UTC)
[Fri Nov 09 2018 06:28:40 GMT+0000 (UTC)] INFO [Incoming] admin: test
[Fri Nov 09 2018 06:28:40 GMT+0000 (UTC)] INFO Message sent to hubot brain.
[Fri Nov 09 2018 06:28:40 GMT+0000 (UTC)] DEBUG No listeners executed; falling back to catch-all
```
My hubot coffee script is pretty simple:
```
module.exports = (robot) ->
  robot.hear /^test$/i, (res) ->
   res.send "Test? TESTING? WE DON'T NEED NO TEST, EVERYTHING WORKS!"

  robot.respond /^test$/i, (res) ->
   res.send "Test? TESTING? WE DON'T NEED NO TEST, EVERYTHING WORKS!"
```

It seems I have two issues:
1) Hubot doesn't register itself as online agent when It's the only Livechatagent
2) Hubot doesn't respond to custom direct messages (maybe script problem?)

**Comment by ruslantagirov** [comment]
UPDATE. This coffeescripts works in DM and Livechats. 
Somehow Hubot doesn't want to use regexp wildcards for direct messages
```
module.exports = (robot) ->
  robot.hear /^test$/i, (res) ->
   res.send "Test? TESTING? WE DON'T NEED NO TEST, EVERYTHING WORKS!"

  robot.respond /test/i, (res) ->
   res.send "Test? TESTING? WE DON'T NEED NO TEST, EVERYTHING WORKS!"
```
So far left the only issue: 
1. Hubot doesn't register itself as online agent when It's the only Livechatagent

**Comment by BrunaChris** [comment]
O meu problema está que em uma das interações, quando ele o usuario, manda o email, ele retorna com o nome do bot, causando a interrupção da interatividade. Será que falta alguma configuração? Pois dentro da sala fazendo testes, a interação acontece normalmente, e externamente não.

 'red brunahk.santos@gmail.com'

Aonde red é o nome do meu bot.

**Comment by chris-aeviator** [comment]
there's now a "assign bot's to livechat" setting in rocketchat

**Comment by gioppoluca** [comment]
This does not work for RASA bot.
Followed documentation on rasa bot and it answer if I post in #genaral channel, but if I post to livechat a queue appers but the webhook created does not call the bot
