### ISSUE TITLE
Send message

### ISSUE THREAD

**Issue by VijiGithub** [RocketChat/hubot-rocketchat#199]
Hi ,

I would like to implement the below feature:

Foreg : User1 is in a private channel say Room1  , and would like to send a message to User2 whos not a memeber of room1 , from the same room.

Room1 : User1:      /SendMessage User2 "I am trying to send a message to you"
syntax :  /command /User_name /Message_to_be_sent

In this way , user doesnt have to leave the existing room and can also send a messsage to others.

**Comment by geekgonecrazy** [comment]
this should be possible with existing methods.  Also if you're just looking for this functionality, in Rocket.Chat we have /msg that'll send a message to a user

**Comment by VijiGithub** [comment]
/msg sends a message to a user but i would like to generate a command where user will type the username  appended with message . can you please tell me how to achieve this?

like : /Send "This will be the user name" "this will be body"
also while the user types username , is it possible to get the list in a dropdown , so that they can select from the dropdown box.

**Comment by VijiGithub** [comment]
I tried writing a script:
 robot.respond /test/i, (res) ->
    str = res.match[1]
    roomname = res.message.room
    username = res.message.user.name
    res.send "A message has been forwarded by #{username} from #{roomname}. Message is #{str}"
    postdata = {
#       "roomid" : "xkwJ2QmjrtAEAfqDE"
       "channel": "#general",
       "text": "This is a test!"
    }
    string_postdata = JSON.stringify(postdata)
    res
      .http("http://10.236.220.177:3777/api/v1/chat.postMessage")
      .headers("User-Id": 'c2QqAEDGcnhST4vPB',"Auth-Token": 'PR6VUwxDWuY66yMrq5yA51aLHgxzLDUQsPFEnTEhsK6',"Content-Type": "application/json")
      .post(string_postdata) (err, resp, body) ->
        result = JSON.parse(resp)
        if result.status == "success"
           res.send "message has been sent"
        else
           res.send "Error #{err}"


This doesnt post the message to the room and doesnt show any error too

**Comment by timkinnane** [comment]
Assuming this is resolved, but it doesn't sound like an adapter issue anyway, more a specific scripting problem with Hubot - the methods to achieve it exist, please ask for help on the open.rocket.chat #hubot channel if you need support.
