### ISSUE TITLE
Node update

### ISSUE THREAD

**Issue by tonobo** [RocketChat/hubot-rocketchat#202]
Is there any possibility to switch to node:v6, because 0.12. is currently end of life.
https://github.com/nodejs/LTS

**Comment by geekgonecrazy** [comment]
It definitely should work with newer versions of node.js. I assume you mean the docker image.  We'd definitely take a PR if you're interested in doing that.

**Comment by JigSawFr** [comment]
I'm using node 7.x without problem :)
