### ISSUE TITLE
Question - Message Display

### ISSUE THREAD

**Issue by hfake** [RocketChat/hubot-rocketchat#205]
Is it possible to have the message display appear differently for different users.  We have a user who would prefer to see the most recent messages at the top of his feed instead of the bottom.  While I don't think this meets everyone's needs, I thought I would inquire if we could change his view to support this preference?

**Comment by geekgonecrazy** [comment]
Currently no its not possible to change how a message is displayed for different people. This repo is for the hubot adapter.  Please open an issue on our main repo.  https://github.com/rocketchat/rocket.chat/issues
