### ISSUE TITLE
Spurious messages from unexpected rooms crashes bot

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/hubot-rocketchat#210]
Depending on the logic of the bot, and how resilient it is to messages from unexpected source, this can cause crashes and security leaks.

This is only a problem when not using LISTEN_ON_ALL_PUBLIC but specifying a set of expected rooms.

Thanks to a thorough analysis by @elespike,  this happens because:
1)  our subscriptions are long living, if the bot user has previously subscribed to a room, the bot will continue to receive messages from that room even if ROCKET_CHAT_ROOM does not include it
2) bot user might (be coaxed into) joining a room AFTER the bot started operation; for example, if someone @ mention the bot in an unexpected public room

2 is especially interesting as it might have security implications in some usage scenarios

**Comment by timkinnane** [comment]
@Sing-Li we briefly discussed a proposal for a new feature in Rocket.Chat to add bot controls to room settings. That would cover this kind of scenario, where bots could be locked out of particular rooms. I think it should be resolved on the Rocket.Chat side regardless, so it applies to all bots, not just Hubots.
I'll close this, but if you think it's still a concern, please add an issue in Rocket.Chat core with `subj: bots` label and I'll follow it up there.
