### ISSUE TITLE
Hubot doesn't reply in private chat to itself

### ISSUE THREAD

**Issue by boazshor** [RocketChat/hubot-rocketchat#212]
Hi,
I'm writing my first bot, using Rocket.Chat :
Rocket.Chat Version: 0.56.0-rc.2
Rocketchat adapter version 1.0.8
NodeJS Version: 4.5.0 - x64

I added to my env variables the following:
export ROCKETCHAT_ROOM=''
export RESPOND_ON_DM=true
export LISTEN_ON_ALL_PUBLIC=true

My bot only responds to messages from public channels but not to messages posted in private ones.
I see the following in the adapter log:
INFO
INFO Logging In
INFO Successfully Logged In
INFO rid:  []
INFO All rooms joined.
INFO Preparing Meteor Subscriptions..
INFO Subscribing to Room: __my_messages__
INFO Successfully subscribed to messages
INFO Setting up reactive message list...

When I send a private message with instructions to the bot I see the following, but no response from the bot: 
INFO Message received with ID id

Any ideas?

**Comment by vinny95** [comment]
Same for me : everything's fine except talking with the bot through DM.
I tried to use env var RESPOND_TO_DM or not, same issue.

**Comment by geekgonecrazy** [comment]
@vinny95 private groups the bot has to actually be invited to, once they are invited to it it will answer messages.

**Comment by N4IR0** [comment]
@geekgonecrazy But the bot also does not reply on a direct chat.

**Comment by xurizaemon** [comment]
This seems to be also reported in #227?

**Comment by Sing-Li** [comment]
@vinny95   make sure you set `RESPOND_TO_DM=true` 

And upcoming fix in 1.0.11  should cure this.   Please report success or problem here after trying 1.0.11 - thanks.
