### ISSUE TITLE
hubot script how to get Room name？

### ISSUE THREAD

**Issue by thinkeridea** [RocketChat/hubot-rocketchat#213]
I try to use hubot control permissions, I think most hubot all function can be applied to join in the Room, but some will only respond to the designated person or Room, at this time I can get to the Room ID, but can't get Room Name, how should do?

**Comment by geekgonecrazy** [comment]
you'll need to access the `getRoomId` method on the adapter and pass the roomid to it.  You'll need the bot role assigned to the user in rocket.chat for this function to work also.

**Comment by thinkeridea** [comment]
This method can only obtain the roomId, but unable to get to the room name

**Comment by JigSawFr** [comment]
@thinkeridea i've the same problem, i'm unable to retrieve room name from a roomID.

```getRoomId: (room) =>
		@tryCache _roomIdCache, 'getRoomIdByNameOrId', room, 'Room ID'```

@geekgonecrazy as you can see you can obtain the RoomId by name or id, but if we want to get the room name from an id, there is not method for this in driver.

**Comment by thinkeridea** [comment]
@JigSawFr I know simple increase Rocket. Chat service API can quickly realize demand, but I'm meteor is not very familiar with, the modified build always fail (perhaps China's firewall), also in trying to have some progress

**Comment by JigSawFr** [comment]
@thinkeridea yes, rocket api has a method to get info from a room by ID : https://rocket.chat/docs/developer-guides/rest-api/channels/info
And it's returning all info with it's name !

**Comment by thinkeridea** [comment]
@JigSawFr I added the server methods getRoomNameById , maintain and present model is consistent, now also in testing availability, specific submission: https://github.com/thinkeridea/Rocket.Chat/commit/231cdaa26ca203d1c4ea4ac2623626a744939635

**Comment by thinkeridea** [comment]
@JigSawFr @geekgonecrazy My practice is successful, very convenient, hubot rocketchat adapter changes: https://github.com/thinkeridea/hubot-rocketchat/commit/f84f50480adaa683480d1d7885bcb6a4ac7e1b4b

![image](https://cloud.githubusercontent.com/assets/12491807/26502992/9200a9b8-4271-11e7-92e3-ba31d9b05543.png)

**Comment by JigSawFr** [comment]
@thinkeridea, finally we have created a service for your scripts which can now use rocket chat api to have more need functions as for example: getRoomNameById, sendPrivateMessage, etc.. detect room type etc..

**Comment by geekgonecrazy** [comment]
@thinkeridea you rock!  Looks like when 0.57.0 lands you will be able to simply call that method! :)

**Comment by thinkeridea** [comment]
@JigSawFr @geekgonecrazy I implemented a simple hubot deployment script automatically, if interested can help add some functions, I will add more documents and assist in the next.
https://github.com/thinkeridea/hubot-gitlab-deploy
