### ISSUE TITLE
Hubot failed to respond to chan as configured

### ISSUE THREAD

**Issue by vinny95** [RocketChat/hubot-rocketchat#219]
Hi,
I have installed : 
Rocket.Chat Version: 0.56.0
Rocketchat adapter version 1.0.8
Hubot last version

I tried to make hubot respond only to a specific room : 
export ROCKETCHAT_ROOM='test'
export LISTEN_ON_ALL_PUBLIC=false
export RESPOND_DM=true

=> my bot does answer to ALL chan, and not via DM : 
[Fri Jun 30 2017 15:48:28 GMT+0200 (CEST)] INFO [Incoming] user: !ping
[Fri Jun 30 2017 15:48:28 GMT+0200 (CEST)] INFO Message sent to hubot brain.
[Fri Jun 30 2017 15:48:28 GMT+0200 (CEST)] INFO Sending Message To Room: GENERAL
[Fri Jun 30 2017 15:48:28 GMT+0200 (CEST)] INFO Looking up Room ID for: GENERAL
[Fri Jun 30 2017 15:48:28 GMT+0200 (CEST)] INFO Message received with ID id
[Fri Jun 30 2017 15:48:33 GMT+0200 (CEST)] INFO Message received with ID id
[Fri Jun 30 2017 15:48:33 GMT+0200 (CEST)] INFO Message receive callback id 4fH3jvQKse9uoHCjN ts Fri Jun 30 2017 15:48:33 GMT+0200 (CEST)
[Fri Jun 30 2017 15:48:33 GMT+0200 (CEST)] INFO [Incoming] user: !ping
[Fri Jun 30 2017 15:48:33 GMT+0200 (CEST)] INFO Message sent to hubot brain.
[Fri Jun 30 2017 15:48:33 GMT+0200 (CEST)] INFO Sending Message To Room: SgDspaBEss2BcMX3L
[Fri Jun 30 2017 15:48:33 GMT+0200 (CEST)] INFO Looking up Room ID for: SgDspaBEss2BcMX3L
[Fri Jun 30 2017 15:48:33 GMT+0200 (CEST)] INFO Message received with ID id

When I change options to : 
export ROCKETCHAT_ROOM=''
export LISTEN_ON_ALL_PUBLIC=true
export RESPOND_DM=true

My bot still does not respond to DM, I only see this : 
[Fri Jun 30 2017 15:48:37 GMT+0200 (CEST)] INFO Message received with ID id

Do you have any idea ?

vinny

**Comment by localguru** [comment]
same here

**Comment by vinny95** [comment]
is there some ways to debug more closely it ?

Not responding to DM is polluting "global" channels so it prevent us to have too many users.

**Comment by timkinnane** [comment]
This should be resolved in recent versions, especially on develop branch because the new SDK driver includes unit tests for exactly this scenario.
