### ISSUE TITLE
Add emoji reactions to messages

### ISSUE THREAD

**Issue by rogerpfaff** [RocketChat/hubot-rocketchat#222]
I tried to set an emoji to a message with callMethod and I called this function https://rocket.chat/docs/developer-guides/realtime-api/method-calls/set-reaction/

The only response I get from this call is "pending"

```
module.exports = (robot) ->
        robot.respond /room/i, (res) ->
                params = [
                        ":nerd:",
                        res.message.id
                ]
                robot.adapter.callMethod "setReaction",params, (response) ->
                        console.log(response)
```

**Comment by geekgonecrazy** [comment]
@rogerpfaff callMethod returns a promise.  Try this:

```
module.exports = (robot) ->
        robot.respond /room/i, (res) ->
                params = [
                        ":nerd:",
                        res.message.id
                ]
                robot.adapter.callMethod('setReaction', params).then (response) ->
                  console.log response
                  return
```

**Comment by rogerpfaff** [comment]
I tried this. But there is no response and no smiley added to a message in RC.

**Comment by geekgonecrazy** [comment]
@rogerpfaff ok so you actually just specify the params right after the call.  We take and then pass as an array.  So this works:
```
module.exports = function (robot) {
    robot.respond(/abc/i, function (res) {
        console.log('hiiiit!');
        robot.adapter.callMethod('setReaction', ':nerd:', res.message.id).then(function(response) {
            console.log(response);
        });
    });
};
```

**Comment by xzoltan** [comment]
Hi, I tried using your provided code but I am running into a permission issue:

`[Wed Dec 12 2018 18:35:48 GMT+0100 (Mitteleuropäische Zeit)] ERROR [setReaction] Error: { isClientSafe: true,
  error: 'error-not-allowed',
  reason: 'Not allowed',
  details: { method: 'setReaction' },
  message: 'Not allowed [error-not-allowed]',
  errorType: 'Meteor.Error' }
(node:5144) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
`

The RocketChat documentation does not mention a permission for reacting to other users' messages
