### ISSUE TITLE
Info Logging

### ISSUE THREAD

**Issue by localguru** [RocketChat/hubot-rocketchat#223]
Hi,

how do I disable INFO logging, e.g. messages "INFO [Incoming] ....", without removing line 

```
@robot.logger.info "[Incoming] #{newmsg.u.username}: #{if newmsg.file? then newmsg.attachments?[0]?.title else newmsg.msg}"
```

from hubot-rocketchat/src/rocketchat.coffee.

Something like
```
export DEBUG_LEVEL=warn
```
doesn't work.

Ciao

**Comment by localguru** [comment]
Ah, it's e.g.

```
export HUBOT_LOG_LEVEL="error"
```

**Comment by geekgonecrazy** [comment]
@localguru ah!  Yes its a hubot level thing.  We might should add to our README in our list of environment variables to aid others

**Comment by localguru** [comment]
okay, see PR #241
