### ISSUE TITLE
Method 'getRoomNameById' not found

### ISSUE THREAD

**Issue by bentsea** [RocketChat/hubot-rocketchat#225]
I've managed to work through most of the issues I've experienced when trying to get hubot running, I've got it successfully joined to all rooms, but any time a message is received incoming the following error is generated:

[Fri Jul 14 2017 19:44:02 GMT+0000 (UTC)] ERROR Unable to get room name: {"error":404,"reason":"Method 'getRoomNameById' not found","message":"Method 'getRoomNameById' not found [404]","errorType":"Meteor.Error"} Reason: Method 'getRoomNameById' not found

Here's the full log from start to first message received:

[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Starting Rocketchat adapter version 1.0.9...
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: bot
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO I will also respond to my Rocket.Chat username as an alias: hubot
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] WARNING No services ROCKETCHAT_ROOM provided to Hubot, using 
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Connecting To: localhost:3000
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Successfully connected!
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO 
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Logging In
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Successfully Logged In
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO rid:  []
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO All rooms joined.
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Subscribing to Room: __my_messages__
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Successfully subscribed to messages
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] INFO Setting up reactive message list...
[Fri Jul 14 2017 19:45:02 GMT+0000 (UTC)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.

Your hubot-scripts.json is empty, so you just need to remove it.
[Fri Jul 14 2017 19:45:03 GMT+0000 (UTC)] ERROR hubot-heroku-keepalive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s | grep web.url | cut -d= -f2)`
[Fri Jul 14 2017 19:45:03 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Fri Jul 14 2017 19:45:08 GMT+0000 (UTC)] INFO Message received with ID id
[Fri Jul 14 2017 19:45:08 GMT+0000 (UTC)] INFO Message receive callback id L4GYzb3v7uejDLk6h ts Fri Jul 14 2017 19:45:08 GMT+0000 (UTC)
[Fri Jul 14 2017 19:45:08 GMT+0000 (UTC)] INFO [Incoming] bentsea: hubot help
[Fri Jul 14 2017 19:45:08 GMT+0000 (UTC)] INFO Looking up Room Name for: t774jC4fPnt4ySkp7
[Fri Jul 14 2017 19:45:08 GMT+0000 (UTC)] ERROR Unable to get room name: {"error":404,"reason":"Method 'getRoomNameById' not found","message":"Method 'getRoomNameById' not found [404]","errorType":"Meteor.Error"} Reason: Method 'getRoomNameById' not found

Any help that could be provided would be appreciated :)

**Comment by geekgonecrazy** [comment]
What version are you running on Rocket.Chat server?

**Comment by bentsea** [comment]
0.56.0
--

**Comment by geekgonecrazy** [comment]
Ok seems the PR that added it https://github.com/RocketChat/Rocket.Chat/pull/7102 targeted master so was not included in the 0.57.0 release.  

Will try to get this resolved asap.  But you will likely need to upgrade Rocket.Chat when this is resolved.  1.0.8 of the adapter shouldn't have this problem

**Comment by bentsea** [comment]
Thank you so much! Would the following line successfully setup the correct version of the adapter? 

yo hubot --adapter="rocketchat@1.0.8"

**Comment by geekgonecrazy** [comment]
should be!  If that doesn't do it, edit the package.json file in your bots folder and change the version to 1.0.8 and then do `npm install` and that should switch the version.  :+1:

**Comment by geekgonecrazy** [comment]
@bentsea sorry I was wrong.  Upgrading to 0.57.2 will allow that method

**Comment by lucasvanhalst** [comment]
@geekgonecrazy 0.57.1 already includes the method so he could also use that

**Comment by geekgonecrazy** [comment]
@lucasvanhalst sure, but 0.57.2 includes more bug fixes which should help in general.

I'll go ahead and close this though.  :+1:

**Comment by antgel** [comment]
@geekgonecrazy Confused - it's not in current `develop`, shouldn't `develop` contain everything in `master` and some other stuff too? ;)

**Comment by lucasvanhalst** [comment]
@antgel that's what got me confused as well, I've no idea why 0.57.x contains changes that aren't in develop yet

**Comment by geekgonecrazy** [comment]
@antgel / @lucasvanhalst 

It confused me too.  :grin: basically the PR that added that targeted the master branch instead of the develop branch.

So when it was merged it made it into the release.. but was never added to the develop branch.  We have a pull request open we are syncing the things added in master back down.
