### ISSUE TITLE
message too long to display in rocket.chat ?

### ISSUE THREAD

**Issue by vinny95** [RocketChat/hubot-rocketchat#228]
Hi,
I send a string message through hubot to rocket.chat 0.57.2.

With the shell adapter, hubot is sending correctly the full message.
With rocket.chat adapter, the message is not sent : 
in hubot it is stopped at "Preparing message from string"
[Tue Jul 25 2017 10:52:58 GMT+0200 (CEST)] DEBUG Executing listener callback for Message '!xxx yyyy'
[Tue Jul 25 2017 10:52:58 GMT+0200 (CEST)] INFO Sending Message To Room: 3tTqB4GMnq7qHQSJX
[Tue Jul 25 2017 10:52:58 GMT+0200 (CEST)] DEBUG Found cached Room ID for 3tTqB4GMnq7qHQSJX: 3tTqB4GMnq7qHQSJX
[Tue Jul 25 2017 10:52:58 GMT+0200 (CEST)] DEBUG Preparing message from string

is there a limit in message size to send it to rocket.chat ?

If I truncate the message to the first 200 cars, it is sent.

vinny

**Comment by geekgonecrazy** [comment]
yes there is.  Its configurable in adminstration->messages
