### ISSUE TITLE
bot is not connecting with latest version of rocket.chat

### ISSUE THREAD

**Issue by oinirio** [RocketChat/hubot-rocketchat#23]
After a clean clone of both chat and bot, the bot will not response to anything

```
[Tue Jul 28 2015 15:11:53 GMT+0000 (UTC)] WARNING No services ROCKETCHAT_URL provided to Hubot, using 10.0.0.121:3000

[Tue Jul 28 2015 15:11:53 GMT+0000 (UTC)] WARNING No services ROCKETCHAT_ROOM provided to Hubot, using general

[Tue Jul 28 2015 15:11:53 GMT+0000 (UTC)] WARNING No services ROCKETCHAT_USER provided to Hubot, using rocketbot

[Tue Jul 28 2015 15:11:53 GMT+0000 (UTC)] INFO running rocketchat
[Tue Jul 28 2015 15:11:53 GMT+0000 (UTC)] INFO login
[Tue Jul 28 2015 15:11:54 GMT+0000 (UTC)] INFO logged in
[Tue Jul 28 2015 15:11:54 GMT+0000 (UTC)] INFO joined room
[Tue Jul 28 2015 15:11:54 GMT+0000 (UTC)] INFO prepare meteor subscriptions
```

**Comment by Sing-Li** [comment]
Yes.  I think we're out of sync with the latest schema.  Might you be able to help with a fix?

**Comment by bryanbecker** [comment]
I don't know how to submit a change request, but I fixed the issue:

on rocketchat_driver.coffee, line 7 change from 
`_messageCollection = 'data.ChatMessage'`
to
`_messageCollection = 'rocketchat_message'`

**Comment by Sing-Li** [comment]
@bryanbecker -  awesome!    If you would like to submit a PR, please:
1.  Fork this repo (top right button)
2.  In your forked copy, [follow these instructions](https://help.github.com/articles/editing-files-in-your-repository/) to edit the code and create the Pull Request.

@oinirio  - please try the proposed fix and let us know if everything works for you again.

**Comment by bryanbecker** [comment]
@Sing-Li Thanks for the instructions!  I think I submitted the change correctly

**Comment by oinirio** [comment]
@bryanbecker @Sing-Li it works flawlessly thanks

**Comment by Sing-Li** [comment]
@oiniro - thx   :smile:
@byanbecker - great!  Your changes are now in the master of the forked repo.  Just a couple of clicks away to PR.  Please see the main page of your cloned repos.  Note `Pull Request` on the right side, and click it.
![temp1](https://cloud.githubusercontent.com/assets/122633/8957811/02bb7310-35cf-11e5-8da7-a5d5dcd51df2.png)
Then just click the green "Create pull request" button, and follow through.  
![temp2](https://cloud.githubusercontent.com/assets/122633/8957896/7ff16d8a-35cf-11e5-9179-5bd60d92526a.png)

**Comment by bryanbecker** [comment]
Alright, done.

Why is it called a 'pull request'?  That's confusing to me, when it seems like I'm pushing the changes

**Comment by Sing-Li** [comment]
Because a 'contributor' proposes a change, and *pushes* from his/her fork to the original master branch; then the owner(s) of the original project considers the proposed changes and optionally *pull* the contributor's changes into his/her code.   In this sense, a contributor creates a *pull request*.

**Comment by bryanbecker** [comment]
ahh, ok... that clears it up
