### ISSUE TITLE
recommended nodejs and npm version?

### ISSUE THREAD

**Issue by localguru** [RocketChat/hubot-rocketchat#239]
Hi,

what's are the recommended nodejs and npm versions to run hubot-rocketchat?

Ciao!
Marcus

**Comment by localguru** [comment]
I run it with 4.8.4 without problems now. But some infos about that would be nice.

**Comment by geekgonecrazy** [comment]
I know this is super delayed.  But this depends 100% on hubot.   I've used up to 6.x with out issues.  Haven't tried 8.x yet
