### ISSUE TITLE
Permissions error when attempting to run Docker image

### ISSUE THREAD

**Issue by willemmerson1** [RocketChat/hubot-rocketchat#243]
Running the following:

docker run -it -e ROCKETCHAT_URL=x.x.x.x:3000 -e ROCKETCHAT_ROOM='' -e LISTEN_ON_ALL_PUBLIC=true -e ROCKETCHAT_USER=botname -e ROCKETCHAT_PASSWORD=passwordremoved -e ROCKETCHAT_AUTH=password -e BOT_NAME=clarobot -v $PWD/scripts rocketchat/hubot-rocketchat

Error:

`npm ERR! Linux 3.10.0-693.2.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hubot-diagnostics" "hubot-help" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-rules" "hubot-shipit"
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! path /home/hubot/node_modules/hubot-help/script
npm ERR! code ENOTEMPTY
npm ERR! errno -39
npm ERR! syscall rmdir

npm ERR! ENOTEMPTY: directory not empty, rmdir '/home/hubot/node_modules/hubot-help/script'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/hubot/node_modules/hubot-help/script'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: ENOTEMPTY: directory not empty, rmdir '/home/hubot/node_modules/hubot-help/script']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/hubot/node_modules/hubot-help/script' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hubot/npm-debug.log`

**Comment by bwilliam79** [comment]
I ran into this same issue and was able to get mine to start by not listing the hubot-help script in the EXTERNAL_SCRIPTS option:

docker run -d --name=<container name> --restart=always --link rocketchat:rocketchat -e ROCKETCHAT_URL=rocketchat:3000 -e ROCKETCHAT_ROOM='<room name>' -e LISTEN_ON_ALL_PUBLIC=true -e ROCKETCHAT_USER=<bot user> -e ROCKETCHAT_PASSWORD=<bot password> -e ROCKETCHAT_AUTH=password -e BOT_NAME=<bot name> **-e EXTERNAL_SCRIPTS=hubot-scripts-stock,hubot-forecastio,hubot-victory** -e HUBOT_FORECAST_IO_API_KEY=<api key> -e HUBOT_FORECAST_IO_UNITS=us rocketchat/hubot-rocketchat
