### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by VedranOP** [RocketChat/hubot-rocketchat#245]
Hello,

After initial login i can't log back.
Can you please offer me what is the fastest way to reset rocket chat to initial run to set an admin account?

I have Ubuntu 16.04  and latest version of rocket chat.
Thank you in advance.

**Comment by timkinnane** [comment]
Closing because this seems like a Rocket.Chat config issue, not the adapter. Please comment with more detail to reopen if required.
