### ISSUE TITLE
error: file not found

### ISSUE THREAD

**Issue by gmdutra** [RocketChat/hubot-rocketchat#251]
Hey guys,
Step 26/31 : RUN cd /home/hubot/node_modules/hubot-rocketchat &&   npm install &&   coffee -c /home/hubot/node_modules/hubot-rocketchat/src/*.coffee &&   cd /home/hubot
 ---> Running in d3bb3035a0e3
File not found: /home/hubot/node_modules/hubot-rocketchat/src/*.coffee
The command '/bin/sh -c cd /home/hubot/node_modules/hubot-rocketchat &&   npm install &&   coffee -c /home/hubot/node_modules/hubot-rocketchat/src/*.coffee &&   cd /home/hubot' returned a non-zero code: 1

Dockerfile: https://pastebin.com/xu5vEFKR

Can someone help me?

**Comment by inkWave** [comment]
same here.dont know what to do .

**Comment by diegodorgam** [comment]
hey @gmdutra have you tried removing the line  `coffee -c /home/hubot/node_modules/hubot-rocketchat/src/*.coffee && \` ?

I don't think you actually need that, and it seems that for some reason your shell interpreter is not recognizing the star in `*.coffee` and actually trying to execute `coffee -c /home/hubot/node_modules/hubot-rocketchat/src/.coffee`.

**Comment by inkWave** [comment]
I figure it out . @gmdutra  there is an ADD command :`ADD . /home/hubot/node_modules/hubot-rocketchat `in that dockerfile. So we have to download these project to our local then there will be files to be added.
