### ISSUE TITLE
Mobile app rocket.app+ fails to authenticate with hosted platform

### ISSUE THREAD

**Issue by piersstorey** [RocketChat/hubot-rocketchat#252]
After adding host, receiving login/register page.
On login attempt getting `User has no password set [403]`
Have tested using an incorrect username and getting back wrong username message. This would indicate the host is resolving.
Also a small UX pointer, there is no back to change the host URL once added in the app. I uninstalled and re-installed to test host name alternatives.

**Comment by piersstorey** [comment]
Closing as i have realised it's in the hubot branch and not relevant .. Apologies.

**Comment by geekgonecrazy** [comment]
I'm not sure what you mean by hosted platform.

**Comment by piersstorey** [comment]
It's the primary self hosted chat platform. There are two Android rocket.chat apps. Rocket.chat+ errors as per issue but the original rocket.chat works fine
