### ISSUE TITLE
Only my user record is added to hubot brain. How are users added to hubot?

### ISSUE THREAD

**Issue by edzillion** [RocketChat/hubot-rocketchat#259]
I am having problems with getting `hubot-auth` to save user roles, and I installed `hubot-brain-inspect` to check what was in `brain.users`. 

> ubibot brain show users
> ubibot 2:36 AM
> zgfuB2P5P2ErF6Nyr edzillion

It shows only myself.

Yet, if I use the `onlineUsers `method added in this PR https://github.com/RocketChat/Rocket.Chat/pull/3799 (which really should be documented)

> ubibot list online users
> ubibot 2:33 AM
> Johnny Appleseed, Ed Zillion, Adam Stoppard and Marc Johnstone are currently online
edzillion 2:36 AM

It shows an accurate list. 

How are users added?

**Comment by edzillion** [comment]
For anyone wondering, hubot only stores the users that have interacted with it. I had to make a helper function to add users to the brain:

```
robot.respond(/sync users with brain/i, function(msg) {
    
    if (!userHasRole(robot,msg,'admin'))
      return;

    var promise;
    promise = robot.adapter.callMethod('botRequest', 'allUsers');
    return promise.then(function(rocketChatUsers) {
      if (!rocketChatUsers)
        return console.error('no rocketchat users!');      
      var prevUsers = robot.brain.users();
      var addedUsers = [];
      var user;
      for (var i=0; i<rocketChatUsers.length; i++) {
        if (prevUsers[rocketChatUsers[i]._id]) {        
          continue;
        }
        user = robot.brain.userForId(rocketChatUsers[i]._id, {
          name: rocketChatUsers[i].username,
          alias: rocketChatUsers[i].alias
        });
        user.room = 'ubibot';
        user.roomID = 'Qt2v8pePHzgCihHZF'; //this is the id of the ubibot room
        addedUsers.push(user);
      }
      msg.send(addedUsers.length+" Users added to brain");      
    }, function(error) {
        msg.send("Uh, sorry I don't know, something's not working");
    });
  });
```

**Comment by geekgonecrazy** [comment]
Thanks for sharing!  We almost need a tips and tricks section for useful little snippets like this

**Comment by timkinnane** [comment]
@geekgonecrazy @edzillion - I'd love to start something like that and add a reference to the docs. I don't think it should go in the docs directly, because it will get crowded and make it harder to find the higher priority content. Do either of you have a suggestion for something like a public snippet collection? Apparently you can't use _gists_ in an organisation - maybe we'd need another repo for just adding script snippets in markdown that demonstrate advanced use cases for the adapter.

**Comment by timkinnane** [comment]
Yeah @geekgonecrazy , I don't think it would be surfaced easily in a repo alongside an actual bot implementation codebase. Needs a dedicated and basic collection, preferably indexed somehow. Maybe a GH pages repo, just with markdown files for each tip and an index file linking to them.
We could possibly put that in a subdirectory of the adapter too and exclude it from NPM. Wouldn't add anything for deployments, only a few more KB for developers pulling the repo. Where having the snippets on hand might be useful anyway.

**Comment by timkinnane** [comment]
^ come to think of it, the only file that needs to be published to npm is the index.js

**Comment by geekgonecrazy** [comment]
If that was done the GitHub pages would be available at: https://rocketchat.girhib io/hubot-rocketchat but more importantly actually at: https://rocket.chat/hubot-rocketchat

**Comment by geekgonecrazy** [comment]
Correct

**Comment by timkinnane** [comment]
🎉  http://rocketchat.github.io/hubot-rocketchat/snippets  🎉 

Check it out!

I haven't added a GH pages index yet, because I guess that should be the Readme, but it's under review so we'll wait till it's updated.
