### ISSUE TITLE
Hubot can't connect to RocketChat

### ISSUE THREAD

**Issue by Dropsik** [RocketChat/hubot-rocketchat#265]
Environment:
RocketChat from Snap ver. 0.61.0
Hubot with RocketChat adapter running from Docker

After run docker image, I got:

`ERROR Unable to get room id: {"isClientSafe":true,"error":"error-not-allowed","reason":"Not allowed","details":{"method":"getRoomIdByNameOrId"},"message":"Not allowed [error-not-allowed]","errorType":"Meteor.Error"} Reason: Not allowed
ERROR {"isClientSafe":true,"error":"error-not-allowed","reason":"Not allowed","details":{"method":"getRoomIdByNameOrId"},"message":"Not allowed [error-not-allowed]","errorType":"Meteor.Error"}
ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.`

What I checked:
- I can log in via WebUI with bot credentials
- Bot user have assigned bot role
- Bot role have permission to view-c-room

Seems to the same problem like #123 

Edit:
Problem exist with private channel. In my other environment (the same versions, but RocketChat installed natively) work perfect with private channels

**Comment by geekgonecrazy** [comment]
Make sure the user you are connecting as has the bot role.  Otherwise it will be unable to call the getRoomId function you are getting the error about

**Comment by timkinnane** [comment]
@Dropsik if you're still having this issue, please update with what you've tried because it looks like just a problem with either the bot's role, the room name or some other config. We'll assume it's fixed otherwise.
