### ISSUE TITLE
adapter does not respond to messages using hubot 3.0.1

### ISSUE THREAD

**Issue by amtypaldos** [RocketChat/hubot-rocketchat#266]
After trying a few things I can not get the adapter to work with hubot 3.0.1.  I have tried a bare bones install of hubot with this adapter and still nothing.

I am running node 8.9.3 and hubot-rocketchat adapter 1.0.12

It seems like hubot gets the messages but does not respond, this is me sending two messages `helper ping` and `helper help`:

```
[Fri Mar 02 2018 15:53:38 GMT-0500 (EST)] INFO [Incoming] alex: helper ping
[Fri Mar 02 2018 15:53:38 GMT-0500 (EST)] INFO Checking to see if method: getRoomNameById exists
[Fri Mar 02 2018 15:53:38 GMT-0500 (EST)] INFO Looking up Room Name for: ZNC4NrsK8d2FvL2tu
[Fri Mar 02 2018 15:53:38 GMT-0500 (EST)] INFO setting roomName: bots
[Fri Mar 02 2018 15:53:38 GMT-0500 (EST)] INFO Message sent to hubot brain.
[Fri Mar 02 2018 15:53:48 GMT-0500 (EST)] INFO Message received with ID id
[Fri Mar 02 2018 15:53:48 GMT-0500 (EST)] INFO Message receive callback id 64vFdmifCpF8PjBaR ts Fri Mar 02 2018 15:53:48 GMT-0500 (EST)
[Fri Mar 02 2018 15:53:48 GMT-0500 (EST)] INFO [Incoming] alex: helper help
[Fri Mar 02 2018 15:53:48 GMT-0500 (EST)] INFO setting roomName: bots
[Fri Mar 02 2018 15:53:48 GMT-0500 (EST)] INFO Message sent to hubot brain.
```

**Comment by timkinnane** [comment]
I'm working on a fix for this, will update early next week.

**Comment by amtypaldos** [comment]
Fantastic, thanks so much! Can you share the PR when you are done. I'm curious what the actual issue is.

**Comment by timkinnane** [comment]
Hi @amtypaldos please have a look at the current develop branch. It's working with Hubot v3 and we've put up a demo here: https://github.com/RocketChat/hubot-rocketchat-boilerplate
