### ISSUE TITLE
hubot hear all direct messages (not his own direct messages)

### ISSUE THREAD

**Issue by schirrmie** [RocketChat/hubot-rocketchat#274]
Hi, 

I want to write a simple hubot script to update a message. This script works in all public rooms and direct messages to the bot. But it does not work with direct messages to other users.
I tried any of these options:
`ROCKETCHAT_ROOM=""
LISTEN_ON_ALL_PUBLIC=true
#RESPOND_TO_DM=true
`
Is this not possible? Or how can hubot hear all direct messages?

Regards

**Comment by timkinnane** [comment]
@schirrmie that's by design. A bot cannot listen to a direct message between two users. That would be a privacy violation risk.

**Comment by JSzaszvari** [comment]
> @schirrmie that's by design. A bot cannot listen to a direct message between two users. That would be a privacy violation risk.

This.
