### ISSUE TITLE
Both Bot and User be agents of livechat

### ISSUE THREAD

**Issue by AmirHadifar** [RocketChat/hubot-rocketchat#276]
Currently, If someone wanted to have **hubot** in _livechat_, then **hubot** should be the sole agent [according to [here](https://github.com/RocketChat/hubot-rocketchat/issues/195)].

I want to know is it possible to have both Bot and User be agents of _livechat_?

**Comment by renatobecker** [comment]
Yes. You only need to add de Hubot User as a Livechat agent and the Livechat queue will deal with it as a normal user.

**Comment by BrunaChris** [comment]
Boa tarde, 

meu bot responde normalmente, ate a interação com leitura de email, onde ele retorna com o nome do hutbot mais email, impedindo de dar prosseguimento, alguem sabe se é alguma configuração que falta? pois se faço testes dentro da sala, a interação acontece normalmente. agora externamente não.

``` text: 'red brunahk.santos@gmail.com'

Esse red é o nome do robô.
