### ISSUE TITLE
how to get a username 

### ISSUE THREAD

**Issue by shellyng** [RocketChat/hubot-rocketchat#299]
I try to get a user name but, when someone else calls the bot the name changes. 

I'm using this command: name = context.response.message.user.id

**Comment by timkinnane** [comment]
@shellyng What do you mean the name changes? Are you trying to get the name of the user messaging the bot? That would change if the message comes from someone else... 🤷‍♂️

**Comment by shellyng** [comment]
ah ok i understand , but how i get the username and when the other person call the bot this name doesn't change?
