### ISSUE TITLE
Allow bot name to be omitted for direct messages

### ISSUE THREAD

**Issue by withinfocus** [RocketChat/hubot-rocketchat#306]
As we updated to v2 (and perhaps its interaction with hubot v3) we noticed that direct messages to a bot still require its name be specified e.g. `mybot do this` instead of `do this`. When direct messaging the bot name should be implied and allowed to be omitted. This was the case with v1.

**Comment by timkinnane** [comment]
This behaviour exists unchanged. See here:
https://github.com/RocketChat/hubot-rocketchat/blob/930d085472bb9afa122721fa1b0bec59a783b86b/index.js#L113-L116

If the room is a DM and the message doesn't already start with the bot's name, it is prepended in the adapter before being processed by Hubot.

Are you on RC version 0.72? There's a core issue that might be effecting your bot's ability to determine if it's in a DM. https://github.com/RocketChat/Rocket.Chat/issues/12574

**Comment by withinfocus** [comment]
Wild -- we thought it was a coincidence with an `npm update` but we are indeed on 0.72 and this could be it.

**Comment by withinfocus** [comment]
The 0.72.3 snap went live this weekend and we confirmed this is fixed. Thanks for the link.
