### ISSUE TITLE
Add env variable to enable use of self-signed SSL certs

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/hubot-rocketchat#35]
Some users are testing with self-signed certs

Add an explicit  environment variable,  to bypass the SSL cert validity check, and enable use of self-signed SSL cert

**Comment by richardwlu** [comment]
@Sing-Li Is there a way around this for now?

**Comment by richardwlu** [comment]
I'm getting a `SELF_SIGNED_CERT_IN_CHAIN` error. Has anyone figured out a workaround for this?

**Comment by renanvicente** [comment]
As a workaround you can set NODE_TLS_REJECT_UNAUTHORIZED = "0" on your docker-compose. For the code, I believe you could add something like ROCKETCHAT_SELFSIGNED_CERT and if set as true then execute process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"

**Comment by juanramb** [comment]
+1

**Comment by col-panic** [comment]
Related https://forums.rocket.chat/t/error-self-signed-certificate-in-certificate-chain/2495
