### ISSUE TITLE
Bot ignore other bots

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/hubot-rocketchat#36]
Need to respect other bots.  In a multi-bots environment.   Bots 'chatter' can ping-pong for minutes ! :open_mouth:

**Comment by geekgonecrazy** [comment]
The idea here is maybe once roles are assigned it ignores input from other bots?

**Comment by Sing-Li** [comment]
:+1:

**Comment by FibreFoX** [comment]
Even this is a rather old issue, some things crossed my mind:
What if I set up two different bots in the same channel, talking to each other?

The idea is that I can "connect" two different bots (one is jenkins, the other is some fancy libvirt-bridge), where the jenkins.bot talks to libvirt.bot asking for a fresh VM ... e.g. for running tests for it. To make the communication transparent to Ops, this might happen in a "read-only"-channel visible to Dev-/SysOps.

This means, that ignoring ALL bots should make it impossible to have such setup, maybe it should include some blacklist/whitelist of other bots ?!

**Comment by xiaket** [comment]
I agree with @FibreFoX , as a DevOps engineer, I definitely want to build something that he had suggested. To ignore all bots at an adapter's level seemed really odd to me.

And I further suggest that we should do nothing to change the current situation. It is rather easy for a bot to recognise other bots and ignore what the bot had said, so as to avoid an endless bot-chat loop.

**Comment by timkinnane** [comment]
With recent updates to the SDK and adapter develop branch (soon to be released), all messages from a bot are given the `.bot` attribute. Scripts can assess that property on received messages to ignore bots if they need to.

**Comment by joshuaspence** [comment]
Can you provide an example of how to do this? I've updated `hubot`, `hubot-rocketchat` and `@rocket.chat/sdk` to the latest versions but still can't seem to determine whether the message is coming from a bot user.
