### ISSUE TITLE
Bot not completing login process?

### ISSUE THREAD

**Issue by indiggio** [RocketChat/hubot-rocketchat#37]
I'm running the bot via command line: bin\hubot -a rocketchat.
I've got DEBUG enabled, so I can get as much output as possible.
Here's the output during startup, which just hangs at the end.
[Mon Sep 21 2015 11:41:30 GMT-0500 (CDT)] INFO logged in
[Mon Sep 21 2015 11:41:30 GMT-0500 (CDT)] INFO joining room
[Mon Sep 21 2015 11:41:30 GMT-0500 (CDT)] INFO joined room
[Mon Sep 21 2015 11:41:30 GMT-0500 (CDT)] INFO Preparing Subscriptions
[Mon Sep 21 2015 11:41:30 GMT-0500 (CDT)] INFO prepare meteor subscriptions
[Mon Sep 21 2015 11:41:30 GMT-0500 (CDT)] INFO data.roomid == general

I expect to see "subscription ready" output from
https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat.coffee#L33
but it never comes out as it's the very next line in the code??

Thanks!

**Comment by Sing-Li** [comment]
Try "GENERAL" in upper case?

**Comment by indiggio** [comment]
Bingo!
Using uppercase for the roomid fixed it.

Thx!
