### ISSUE TITLE
'rocketchat.js' not found

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/hubot-rocketchat#38]
![2015-09-22_14-00-05](https://cloud.githubusercontent.com/assets/2517921/10017875/457b3b16-6132-11e5-88ce-2040ab3adeb1.png)

What am I doing wrong? :/

**Comment by Sing-Li** [comment]
@k0nsl   Please use the new container   rocketchat/hubot-rocketchat      
The one under my username is no longer actively maintained.   The new one is kept updated with every npm module revision.

**Comment by kakawait** [comment]
@Sing-Li using `docker run -it --rm --net host -e ROCKETCHAT_URL=http://myinstance:3000/ -e ROCKETCHAT_ROOM=GENERAL -e ROCKETCHAT_USER=bot -e ROCKETCHAT_PASSWORD=bot -e BOT_NAME=bot -e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help -e DEV=true -v $PWD:/home/hubot/node_modules/hubot-rocketchat rocketchat/hubot-rocketchat` I have the same issue

**Comment by geekgonecrazy** [comment]
When mounting current directory to `/home/hubot/node_modules/hubot-rocketchat` you need to have this repos contents in the folder.

That is purely so you can work on the adapters code its self.  So if you don't need to work on the adapter you wouldn't want to do that.  

If you want to write scripts for the bot and have them included try:

`-v $PWD:/home/hubot/scripts`

**Comment by geekgonecrazy** [comment]
@k0nsl did you get this resolved?

**Comment by Sing-Li** [comment]
Please reopen if you still have problem.
