### ISSUE TITLE
hubot does not finish login

### ISSUE THREAD

**Issue by fanbin** [RocketChat/hubot-rocketchat#44]
Hubot-rocketchat cannot successfully finish loggin. 

ERROR message follows:

![selection_001](https://cloud.githubusercontent.com/assets/238051/10063805/52f0b668-62a4-11e5-8f57-29ee917ee4cb.png)

I am using latest rocket.chat master branch, ```HEAD:1875e3```   (Sep 22), as well as latest hubot-rocketchat (Sep 24). 

Hubot-rocketchat was started in development mode (hubot -a rocketchat).

**Comment by Sing-Li** [comment]
use GENERAL <-- all upper case

**Comment by fanbin** [comment]
tried that, same error. No idea why.

**Comment by geekgonecrazy** [comment]
@fanbin try pulling the latest from rocket.chat.  Because the 22nd is for sure not the latest.  That should solve your problem :)

**Comment by fanbin** [comment]
@geekgonecrazy  Great! Pulling the latest code solves my problem.
