### ISSUE TITLE
Message does not appear in RocketChat

### ISSUE THREAD

**Issue by Dbzman** [RocketChat/hubot-rocketchat#53]
Hey guys,

I tried to use the docker images of RocketChat (0.5.0) with the latest hubot-rocketchat.
In the logs of RocketChat I see the following:
```
[functions] RocketChat.sendMessage ->  arguments: { '0': { _id: 'vc23ZEswYR5hu9q8q', username: 'timo.litzius' },
  '1': { rid: '4K5xMvFttPTGKiNse', msg: 'try' },
  '2': { _id: '4K5xMvFttPTGKiNse', t: 'c', name: 'botty' } }
{ rid: '4K5xMvFttPTGKiNse',
  msg: 'try',
  ts: Sun Oct 04 2015 15:17:26 GMT+0000 (UTC),
  u: { _id: 'vc23ZEswYR5hu9q8q', username: 'timo.litzius' },
  _id: 'bLczJQMam4p3xR2xn' }
ROCKETCHATADAPTER -> send
send 4K5xMvFttPTGKiNse: Trying is the first step towards failure. (timo.litzius)
```
Looks like the bot can pickup my messages but the response never appears in the channel.
Any ideas?

Cheers
Timo

**Comment by geekgonecrazy** [comment]
Please use the latest with the RocketChat/Rocket.chat image.  0.5.0 is very
outdated outdated.

**Comment by Dbzman** [comment]
I currently only see 2 versions of RocketChat:
https://github.com/RocketChat/Rocket.Chat/tags
Am I looking at the wrong location?

**Comment by Sing-Li** [comment]
https://hub.docker.com/r/rocketchat/rocket.chat/

**Comment by Dbzman** [comment]
Thank you!
Sorry for the disruption. I thought the "official" one would be the best: https://hub.docker.com/r/library/rocket.chat/
It now works perfectly. :)

**Comment by geekgonecrazy** [comment]
@Dbzman sorry for the confusion.  Both are "official".  The [rocket.chat](https://hub.docker.com/_/rocket.chat/) image requires an extra set of steps to verify.  We're working on automating it so it'll always be up to date.

**Comment by Dbzman** [comment]
Nice to hear. Thanks for the clarification! :)
