### ISSUE TITLE
Rocket Chat Hubot Adapter is not replying back for the commands

### ISSUE THREAD

**Issue by enterpriseentity** [RocketChat/hubot-rocketchat#55]
Hi,

Whenever i am running hubot with rocket chat adapter, it is giving the following output, and also not going to cli prompt. and if i am ping from Rocket chat url , it is just telling change received with the corresponding ID. There is no reply is coming back to chat window. I have put some external scripts to hear my command.

If i run without the rocket adapter , i am able to hear the command and respond back via Emit or reply.

Please help me to resolve the issue.

D:\webshot\myhubot>bin\hubot -a rocketchat
[Thu Oct 08 2015 17:02:55 GMT+0530 (India Standard Time)] INFO Starting Rocketchat adapter...
[Thu Oct 08 2015 17:02:55 GMT+0530 (India Standard Time)] INFO Once connected to rooms I will respond to the name: GroceryOps
[Thu Oct 08 2015 17:02:55 GMT+0530 (India Standard Time)] INFO Connecting To: 172.28.135.145:3000
[Thu Oct 08 2015 17:02:55 GMT+0530 (India Standard Time)] INFO Successfully Connected!
[Thu Oct 08 2015 17:02:55 GMT+0530 (India Standard Time)] INFO GENERAL
[Thu Oct 08 2015 17:02:55 GMT+0530 (India Standard Time)] INFO Logging In
[Thu Oct 08 2015 17:02:55 GMT+0530 (India Standard Time)] INFO D:\webshot\myhubot\scripts\example.coffee is using deprecated documentation syntax
[Thu Oct 08 2015 17:02:55 GMT+0530 (India Standard Time)] INFO D:\webshot\myhubot\scripts\router.coffee is using deprecated documentation syntax
[Thu Oct 08 2015 17:02:56 GMT+0530 (India Standard Time)] INFO Successfully Logged In
[Thu Oct 08 2015 17:02:56 GMT+0530 (India Standard Time)] INFO Joining Room: GENERAL
[Thu Oct 08 2015 17:02:56 GMT+0530 (India Standard Time)] INFO all rooms joined
[Thu Oct 08 2015 17:02:56 GMT+0530 (India Standard Time)] INFO Successfully joined room: GENERAL
[Thu Oct 08 2015 17:02:56 GMT+0530 (India Standard Time)] INFO Preparing Meteor Subscriptions..
[Thu Oct 08 2015 17:02:56 GMT+0530 (India Standard Time)] INFO Subscribing to Room: GENERAL
[Thu Oct 08 2015 17:02:56 GMT+0530 (India Standard Time)] INFO all subscriptions ready
[Thu Oct 08 2015 17:02:56 GMT+0530 (India Standard Time)] INFO Successfully subscribed to room: GENERAL
[Thu Oct 08 2015 17:02:56 GMT+0530 (India Standard Time)] INFO Setting up reactive message list...
[Thu Oct 08 2015 17:03:02 GMT+0530 (India Standard Time)] INFO Change received on ID hrJtvGtMEYGpwf9ng

**Comment by Sing-Li** [comment]
Would be helpful if you include a message or two where you have tried talking to the bot.

With what you've included, looks like it is fully functional.

I am assuming you are calling it with:

@GroceryOps:  help

**Comment by enterpriseentity** [comment]
I am trying the command from rocket-chat screen:
![rocketchat screen](https://cloud.githubusercontent.com/assets/10217792/10366809/7b825e64-6dea-11e5-87fc-2907530189cc.png)


Once i entered the Message

I can see the logs like below for every message, but the expected behaviour is not happening..

![hubot screen](https://cloud.githubusercontent.com/assets/10217792/10366985/67774726-6deb-11e5-87e4-50f5fe6c08f4.png)

Actually it should fire the http call for the comand "GroceryOps traffic report "

Even i have inspected the message: by putting console.log , in rocketchat_driver.coffee.

I am able see the message in changedMsg = changedMsgQuery.result[0].


Here is the Operations.coffee file:

module.exports = (robot) ->
  robot.hear /traffic report/i, (res) ->
  	robot.http("http://localhost:9050")
    .get() (err, res1, body) ->
    	res.send "Hey! #{body}"

  robot.respond /open the pod bay doors/i, (res) ->
    res.reply "I'm afraid I can't let you do that."

  robot.hear /I like pie/i, (res) ->
    res.emote "makes a freshly baked pie"

  robot.on "commit", () ->
    robot.messageRoom 'room', 'room'
    robot.http("http://localhost:9050")
    .get() (err, res1, body) ->
    	res.send "Got back #{body}"


I dont know what i am missing.

**Comment by enterpriseentity** [comment]
Here is the screenshot for : Message received successfully , but no reaction

![reactivequery](https://cloud.githubusercontent.com/assets/10217792/10367543/c5d12fb4-6dee-11e5-8290-b53f6754fcc4.jpg)

**Comment by enterpriseentity** [comment]
Hey Sing li, Sorry man... Now it is working well..
I did one thing bad. Its my mistake..
I have used the same user for Bot as well as Rocket Chat App also....
That's why it is not reponsed back...
Now i have used seperate user  for Hubot  and Seprate user for Rocket Chat App.. Now it is responding back ....
Anyway , thanks for the quick reply....
Finally it is resolved. Thanks

**Comment by geekgonecrazy** [comment]
@enterpriseentity good to hear you got that.  I was just about to ask you that question :+1: 

Because it only spits out the incoming text if its not being sent from its user account.  The fact that you saw the ID's meant for sure it was seeing them, it just was ignoring them intentionally.

**Comment by m0se** [comment]
Hey @enterpriseentity, could you please provide more details what fiexd the issue?
I'm having the exact same syptomes, only getting "Change received on ID <id>" in the logs and the bot does not respond. Which usernames need to be different? In my case I run the unmodified docker and connect to Rocket Chat with testbot, but also set the bots name to testbot (so that the log reports: "Once connected to rooms I will respond to the name: testbot"). Have tried it with a different names there, but this didn't help.
So I assume you are talking about usernames on a different level. 
Thanks.

**Comment by deenski** [comment]
I second ^

**Comment by jondkelley** [comment]
I third ^

**Comment by timkinnane** [comment]
@jondkelley - please open a new issue, this one was closed over 2 years ago.
