### ISSUE TITLE
rename ROCKETCHAT_URL

### ISSUE THREAD

**Issue by kakawait** [RocketChat/hubot-rocketchat#56]
Can be stupid but I lost 5 min to understand that `ROCKETCHAT_URL` is not asking an `URL` as defined on spec https://url.spec.whatwg.org/#url-syntax because absolute `URL` should have a `scheme`.

```
-e ROCKETCHAT_URL=http://my-instance.local:3000
```

does not work!

It can be renamed by `ROCKETCHAT_INSTANCE` or something else

**Comment by mhurwi** [comment]
Thanks for noting this! I would not have figured it out otherwise.

Docs should definitely clarify what some examples are.

I'm using:

```
ROCKETCHAT_URL=localhost:3000
```

**Comment by geekgonecrazy** [comment]
I agree it is confusing.  We need to take that as input.  Pull off If https we need to take and set ssl to true. Then pass the host on.  If nothing set just default to http

**Comment by teon** [comment]
+1 after long time I just wanted to submit an issue - and found this one.. now connecting works.
