### ISSUE TITLE
Heroku alive exclusion

### ISSUE THREAD

**Issue by giray** [RocketChat/hubot-rocketchat#57]
I get the following error

ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web_url | cut -d= -f2)`

however removing 

 npm uninstall hubot-heroku-keepalive 

causes the bot not to start at all

ERROR Error loading scripts from npm package - Error: Cannot find module 'hubot-heroku-keepalive'

**Comment by geekgonecrazy** [comment]
@giray are you deploying this to heroku?   If not what deployment method?

**Comment by giray** [comment]
@geekgonecrazy no not using heroku ...  just followed https://github.com/RocketChat/hubot-rocketchat/blob/master/README.md  Add adapter to hubot -> New install

**Comment by geekgonecrazy** [comment]
@giray ah!  I think the generator does add that by default.  Just remove from external-scripts.json.  I'll try to find a way to keep it from installing initially and update the tutorial.  

Sorry about that.

**Comment by soedr** [comment]
I'm getting the same error trying to deploy to heroku, even after using:

`heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=https://myappname.herokuapp.com/ --app myappname`

What could be the issue?

**Comment by geekgonecrazy** [comment]
@soedr we might should exclude this module completely.  But this is an error with that module its self.

Maybe something on this page will help: https://github.com/hubot-scripts/hubot-heroku-keepalive

For anything other then experimenting i'd recommend putting your bot on something other then a heroku free dyno.
