### ISSUE TITLE
Auto-subscribe to room when invited

### ISSUE THREAD

**Issue by Theaxiom** [RocketChat/hubot-rocketchat#59]
Currently when you invite the rocketchat hubot to a room, he will not respond to any commands; I am assuming this is because he doesn't have a meteor subscription. In slack, if you invite hubot to a room, he automatically is available to chat with, you do not need to modify the configuration file to add those rooms.

**Comment by geekgonecrazy** [comment]
I agree.  I believe there is a collection we can subscribe to that contains all channels the user is in.

**Comment by tanc** [comment]
This would be very useful.

**Comment by tholu** [comment]
:+1:

**Comment by Sing-Li** [comment]
The default configuration, as updated in the README, supports this now.

Closing ticket.
