### ISSUE TITLE
Define and implement channel / room join policies for bots

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/hubot-rocketchat#6]
This is a tough one. 
- too rigid and some yet-to-be-imagined innovative bot use-cases will be blocked  
- too permissive and it will be open invitation for DoS and assorted abuses

This also depends heavily on the eventual security model / vision (and channels grouping / ownership hierarchy strategy) that the core team has in mind.

For the time being, it is probably wise to err on the permissive side.

What do you guys think?

**Comment by timkinnane** [comment]
@Sing-Li can I close this issue? If the requirement still exists, it should be implemented by the bot role permissions on the Rocket.Chat side, no?

**Comment by Sing-Li** [comment]
@timkinnane  please do.   It is quite outdated.
