### ISSUE TITLE
[Q] getting started

### ISSUE THREAD

**Issue by CrystalMethod** [RocketChat/hubot-rocketchat#60]
* How can I understand der connection between https://github.com/RocketChat/hubot-rocketchat and https://github.com/RocketChat/Rocket.Chat/tree/master/packages/rocketchat-hubot?
* What would be a good starting point for supporting Atlassian products (Jira, Confluence, Stash)? Developer setup?

I'm no expert in Javascript programming but a user of Atlassians toolset and would like to gain practical experience with RocketChat.

**Comment by geekgonecrazy** [comment]
This repo is for the hubot adapter for Rocket.Chat.  This is for sure our recommended way.

The one in the main repo is also hubot / adapter but integrates directly into the app so is harder to work with.

I would personally start with checking out our github / gitlab scripts here: https://github.com/RocketChat/Rocket.Chat.Ops/tree/master/scripts

**Comment by CrystalMethod** [comment]
Thank you for clarifying this. I have a development environment up and running now and will start to examine the examples from Chat.Ops.
