### ISSUE TITLE
Keeping Hubot Alive and Run As Daemon

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/hubot-rocketchat#65]
Just wondering how you guys are keeping Hubot alive and running as a daemon? My first thought was to use Forever, but it looks like Forever expects javascript.

**Comment by geekgonecrazy** [comment]
Everything compiles down to JavaScript so forever would work.  I think a lot of us use pm2

**Comment by richardwlu** [comment]
This is where my lack of experience comes in :(




I took a look at pm2 and it looks promising. I don't run rocket chat with docker, so hubot is running according to its documentation (I generated it using yo). It came with the script in bin/hubot but pm2 looks like it expects a .js file. Can you provide thoughts here?

**Comment by richardwlu** [comment]
I'm using an upstart script in the meantime.

**Comment by tholu** [comment]
@richardwlu Care to share the script you are using?
I'm using the docker image, running as a daemon via ``docker-compose up -d hubot``.

**Comment by richardwlu** [comment]
@tholu I didn't use the docker image to set it all up.

I used the following https://github.com/RocketChat/Rocket.Chat.Website/blob/master/pm2.production.json and edited the env variables. I add the json file to my Hubot home directory and issued a `pm2 start pm2.production.json'. I hope this can lead you to the right direction.
