### ISSUE TITLE
Handle Direct Messages

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/hubot-rocketchat#67]
I am unable to find anything that allows Hubot to respond to direct messages. This is useful so that users can interact with him without spamming the chat.

**Comment by richardwlu** [comment]
@Sing-Li I was wondering if you could provide any thoughts on this? Maybe there is something I am missing.

**Comment by Sing-Li** [comment]
Good idea.  Thanks!

**Comment by richardwlu** [comment]
Thanks for this!

I am not sure how involved this would be but somehow, if talking to the bot in a DM, we don't have to specify an @hubot for all commands.
