### ISSUE TITLE
Hubot Joining Channels Not Defined In ROCKETCHAT_ROOM

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/hubot-rocketchat#68]
I have two Hubot instances running and they are joining channels that I have not specified in their `ROCKETCHAT_ROOM` env variable. Even though they sit in the incorrect public channels, they reply/respond according to what is defined in `ROCKETCHAT_ROOM`.

**Comment by darvs** [comment]
I have encountered a similar problem. According to the logs, my bots only join and subscribe to one channel each, the one defined in their ROCKETCHAT_ROOM.

However, they will HEAR everything that is said in all channels. 

I have tried restarting the server and running only one bot and it seems it still happens so I am not entirely sure it is related to the multiple bots thing, it could only be that somehow there is a problem with subscribing to only one channel?

**Comment by richardwlu** [comment]
Yeah, it doesn't only occur when I have two bots. I loaded up just one bot and it joins up all channels without consent. This leads to confusion for users.

**Comment by geekgonecrazy** [comment]
The presence will show up in any channel the bot has ever been invited to.  It will only actually listen in rooms you assign though.  

If it's listening in more..  Is one of those boys the internal rocketchat bot?  If so this is actually built in to the core of Rocket.Chat.

**Comment by darvs** [comment]
The internal rocketchat bot? I am not sure what you mean. Both of my bots are cloned from hubot with the hubot-rocketchat adapter and I could be very wrong but I don't think there's anything internal to that.

But after a bot has been launched, I can create a new channel, don't invite anybody, and say something in that new channel and that still triggers the bot.

I've got this little script snippet:  

```
  robot.hear /^ping me/i, (res) ->
    res.send('pong!')
```

And here is the log.

```
Joining Room: GENERAL
rid:  [ 'GENERAL' ]
all rooms joined
Successfully joined room: GENERAL
Preparing Meteor Subscriptions..
Subscribing to Room: GENERAL
all subscriptions ready
Successfully subscribed to room: GENERAL
Setting up reactive message list...
```

Here I create a new room called #test1 and don't invite anybody. I join and say 'ping me' in that new channel. The bot answers in the channel. I can't figure out why.

I added a little bit to the trace to see where the message is coming from:

```
Change received on ID W6Zm8yPbbn3KMevKu
Message receive callback id kffhdfaQyzWFms2ie ts Mon Nov 16 2015 07:12:58 GMT-0500 (EST)
[Incoming] darvs@8bzD5wE5MQ8Fuuycj: ping me
Message sent to hubot brain.
Sending Message To Room: 8bzD5wE5MQ8Fuuycj
Change received on ID W6Zm8yPbbn3KMevKu
Change received on ID 7HTh4XuLhrSFvz4Du
Message receive callback id NXDTNSEWBauWYAihP ts Mon Nov 16 2015 07:12:58 GMT-0500 (EST)
```

**Comment by geekgonecrazy** [comment]
Yes there is one you can enable directly inside Rocket.chat that will talk and listen in all rooms.
@sing-li any ideas?  I know some subscription stuff was changed recently.  This is the first I'm seeing of this though

**Comment by Sing-Li** [comment]
@richardwlu @darvs - which version of the npm module are you using, make sure you are on the latest first.

With Rocket.Chat, and many other chats of similar nature (multiple simultaneous clients - web, mobile, others),  it is important to differentiate between MEMBERSHIP to a channel and PRESENCE.

Once a user (or bot) joins a channel, and becomes a member, it usually DOES NOT unjoin for a long long time -- after many many sessions, typically.

Presence in a room, however, is currently voodoo science.  It is easy to capture the information as a user (or bot), who is ALREADY a member, as she/he/it enters a room.   But it is voodoo to determine when him/her/it is no longer there.

**Comment by darvs** [comment]
@sing-li I am using hubot 2.17.0 and hubot-rocketchat 0.0.20 which seem to be the latest for both.

My problem may have to do with subscriptions, though. If I create a completely new channel, NOT mentioned in ROCKETCHAT_ROOM or anywhere else and don't invite anybody, why is a bot receiving public messages for that channel?

**Comment by geekgonecrazy** [comment]
@darvis when you say receive, is this it responding?  Or do you just see activity in the logs?  Just want to make sure we are on the same page.

**Comment by Sing-Li** [comment]
@sampaiodiego ... do we have to explicitly join (become a member of) a public channel before receiving messages from it?   ...  Are all public channel messages stream emitted to all clients?

**Comment by sampaiodiego** [comment]
No, you don't have to join that channel.
All public channel messages are stremead to everyone who wants to receive.

**Comment by Sing-Li** [comment]
@sampaiodiego thanks!  

@darvs ...so it is a Rocket.Chat specific semantic handling of public channels and memberships.

**Comment by darvs** [comment]
@geekgonecrazy The bot will respond on any channel.

@sing-li, @sampaiodiego Ah... I didn't expect that.

So is there a way to filter messages according to the channel it was on, if I want to make a bot that would hear/respond only to a specific channel?

**Comment by Sing-Li** [comment]
@darvs responding is a different issue.

You should only be able to respond to the current channel... Is your bot able to respond to all channels?

**Comment by darvs** [comment]
Yes, the bot is able to respond to all channels.

**Comment by Sing-Li** [comment]
Ok.  Created issue #74 to deliver the expected behavior.  Should be implemented pronto (hopefully).

**Comment by Sing-Li** [comment]
Thanks for working through this with us, guys!
Closing this.  Please reopen if you feel we need more discussion.

**Comment by darvs** [comment]
Thank you very much to you all for your help!

@richardwlu I hope this has answered your questions too. If not I apologize for taking over this thread, our problems seemed very similar.
