### ISSUE TITLE
Restrict hubot visibility of public channels

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/hubot-rocketchat#74]
Since switching to optimized streams, hubot now sees all messages in all public channels (by design).

Filter this list down in the driver to deliver a more 'expected' behavior for hubot scriptors.

And add "process_all_public_channels" as a  *feature*  :grinning:

**Comment by richardwlu** [comment]
Would this limit the bot's presence in public channels to which we only subscribe him to?

**Comment by Sing-Li** [comment]
@richardwlu  No.  

It restricts visibility of bot to messages from channels specified in ROCKETCHAT_ROOM.
