### ISSUE TITLE
start by docker,and logined, but doesn't work

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/hubot-rocketchat#79]
[Thu Nov 26 2015 06:31:46 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
[Thu Nov 26 2015 06:31:46 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: bot
[Thu Nov 26 2015 06:31:46 GMT+0000 (UTC)] INFO Connecting To: 192.168.99.100:80
[Thu Nov 26 2015 06:31:46 GMT+0000 (UTC)] INFO Successfully Connected!
[Thu Nov 26 2015 06:31:46 GMT+0000 (UTC)] INFO GENERAL
[Thu Nov 26 2015 06:31:46 GMT+0000 (UTC)] INFO Logging In
[Thu Nov 26 2015 06:31:46 GMT+0000 (UTC)] INFO Successfully Logged In
[Thu Nov 26 2015 06:31:46 GMT+0000 (UTC)] INFO Joining Room: GENERAL

I send some message on GENERAL room, but it doesn't work

**Comment by tholu** [comment]
@Micjoyce Which message did you send? How is your bot named?

**Comment by geekgonecrazy** [comment]
@Micjoyce can you confirm the docker image used, as well as like @tholu asked what command did you send?  Also have you tried other channels as well?

**Comment by Micjoyce** [comment]
@tholu  I test send "bot help"/"bot pug me"/"pug me" at GENERAL room, but the bot doesn't return any message;
@geekgonecrazy  I also did the test in the other room , but with GENERAL like no return any message 

[Thu Dec 03 2015 09:44:31 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
[Thu Dec 03 2015 09:44:31 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: bot
[Thu Dec 03 2015 09:44:31 GMT+0000 (UTC)] INFO Connecting To: 192.168.99.100:80
[Thu Dec 03 2015 09:44:31 GMT+0000 (UTC)] INFO Successfully Connected!
[Thu Dec 03 2015 09:44:31 GMT+0000 (UTC)] INFO XZGNucBe6utyaqW6G
[Thu Dec 03 2015 09:44:31 GMT+0000 (UTC)] INFO Logging In
[Thu Dec 03 2015 09:44:31 GMT+0000 (UTC)] INFO Successfully Logged In
[Thu Dec 03 2015 09:44:31 GMT+0000 (UTC)] INFO Joining Room: XZGNucBe6utyaqW6G

after that terminal doesn't print anything

**Comment by tholu** [comment]
@Micjoyce Please post your config / commands you use to start hubot.

**Comment by Micjoyce** [comment]
@tholu  there is my commands, rocket.chat run at 192.168.99.100:80
docker run -it -e ROCKETCHAT_URL=192.168.99.100:80 \
    -e ROCKETCHAT_ROOM=GENERAL \
    -e ROCKETCHAT_USER=bot \
    -e ROCKETCHAT_PASSWORD=bot \
    -e BOT_NAME=bot \
    -e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help \
    rocketchat/hubot-rocketchat

Here is what I run rocket. chat Steps：
1、docker run --name db -d mongo --smallfiles；
2、docker run --name rocketchat -p 80:3000 --env ROOT_URL=http://localhost --link db -d rocket.chat

**Comment by tholu** [comment]
It should print something after the "Joining Room"-line. Please try to use the latest docker images and use ``docker-compose`` with an adjusted config file (see https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml and https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-with-Docker).

**Comment by geekgonecrazy** [comment]
Yes it should say something about subscribing after.

Using all docker I would actually recommend using --link rocketchat like:

```
docker run -it -e ROCKETCHAT_URL=rocketchat:80 \
--link rocketchat \
-e ROCKETCHAT_ROOM=GENERAL \
-e ROCKETCHAT_USER=bot \
-e ROCKETCHAT_PASSWORD=bot \
-e BOT_NAME=bot \
-e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help \
rocketchat/hubot-rocketchat
```

This is essentially what the docker-compose image @tholu links to above is doing behind the scene automatically

**Comment by Micjoyce** [comment]
@tholu  @geekgonecrazy  Thank you very much , I have successfully started by docker-compose,I think I need to find a good time to learn how to use docker
