### ISSUE TITLE
Add support for emote 

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/hubot-rocketchat#8]

**Comment by pandajesupport** [comment]
i'm confused, you asked Add support for emote or Remote.

**Comment by geekgonecrazy** [comment]
I don't completely understand the ask on this one :grin:

**Comment by geekgonecrazy** [comment]
I think closed via: https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat.coffee#L213
