### ISSUE TITLE
Notification endpoint?

### ISSUE THREAD

**Issue by tholu** [RocketChat/hubot-rocketchat#80]
Does this adapter expose a notification endpoint, e.g. to use for notifications when builds complete?
Or how can I use this hubot script: https://www.npmjs.com/package/hubot-jenkins-notifier

**Comment by tholu** [comment]
Here is how it works with docker-compose.

First, expose the port of the docker image by adding the following to the hubot-section of your ``docker-compose.yml`` (make sure that the intendation is correct):
```
ports:
    - 3001:8080
```

This exposes the default hubot port 8080 to 3001 on the host. Also make sure to configure your firewall accordingly.

Then you can use the following notification endpoint for the mentioned ``hubot-jenkins-notifier``:

``http://<your-rocket-chat>:3001/hubot/jenkins-notify?room=<roomid>``

Replace <roomid> with either GENERAL or the generated room id, which you can find by checking the hubot logs (``docker-compose logs hubot``).

Can we expose the hubot-port by default in ``docker-compose.yml``?

**Comment by pschonder** [comment]
Do you know, you can send messages to the room via REST?
https://github.com/RocketChat/Rocket.Chat/wiki/REST-APIs

**Comment by tholu** [comment]
@pschonder Thanks, I did not know that! However I'm not aware of a Jenkins notification-plugin using REST APIs currently, I did only know the hubot notification endpoint from the integration with a previous chat solution, so I tried to implement that.

**Comment by geekgonecrazy** [comment]
@tholu you would for sure have to use a script.  The bot its self doesn't expose anything.  It only exposes what the scripts ask to be exposed.

**Comment by tholu** [comment]
@geekgonecrazy Sure, but to communicate with the script, I have to expose the port 8080 on the ``hubot`` docker image to the host. See my comment above and the updated ``docker-compose.yml`` (my PR got already accepted, yay!): https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml

**Comment by geekgonecrazy** [comment]
@tholu Awesome!  We all hangout on https://demo.rocket.chat if you need help with the scripts.

**Comment by ericlakich** [comment]
I'm seeing a strange issue using the hubot-jenkins-notifier where messages from the resulting build can only be sent to the "GENERAL" room. I have a second room named "builds" and my hubot users is a member of that room. I've tried to send the room name in the notification url as "BUILDS", "#BUILDS", "%23BUILDS", 'builds', "#builds", and "%23builds" with no luck. If I change the room name back to "GENERAL", then I see the build messages in the #general channel. Any advice? 

Here is a sample of the notification URL i'm using ...
http://{my server ip}:3001/hubot/jenkins-notify?room=builds&notstrat=FS

**Comment by tholu** [comment]
You have to use the `rid` in the URL. You can find it in the hubot logs. Just look at
`docker-compose logs hubot`.

**Comment by ericlakich** [comment]
What is the best way to cause the 'rid' to be displayed in the log?

**Comment by tholu** [comment]
You see it when the hubot joins the room. Just compare the output with your room list in `docker-compose.yml`. Look after `GENERAL`.

**Comment by ericlakich** [comment]
Should I be running debug logging?

**Comment by tholu** [comment]
What do you see when running `docker-compose logs hubot` ?

**Comment by ericlakich** [comment]
This is my 'hubot' user joining a channel named 'build' ... I replaced the IDs with '{string}' in case they are sensitive ... 

hubot_1 | [Fri Feb 05 2016 00:05:23 GMT+0000 (UTC)] INFO Message received with ID {string}
hubot_1 | [Fri Feb 05 2016 00:05:23 GMT+0000 (UTC)] INFO Message receive callback id {string} ts Fri Feb 05 2016 00:05:23 GMT+0000 (UTC)
hubot_1 | [Fri Feb 05 2016 00:05:23 GMT+0000 (UTC)] INFO [Incoming] hubot: hubot

**Comment by ericlakich** [comment]
Also, when I restart the hubot container, I do see this ...

hubot_1 | [Fri Feb 05 2016 00:12:04 GMT+0000 (UTC)] INFO Looking up Room ID for: ''
hubot_1 | [Fri Feb 05 2016 00:12:04 GMT+0000 (UTC)] INFO Joining Room: ''
hubot_1 | [Fri Feb 05 2016 00:12:04 GMT+0000 (UTC)] INFO rid:  [ '\'\'' ]

**Comment by tholu** [comment]
This seems weird, here it looks like that, and you want either {rid1} or {rid2} if you want to post to room1 or room2:

```
hubot_1 | [Thu Feb 04 2016 12:42:19 GMT+0000 (UTC)] INFO Successfully Logged In
hubot_1 | [Thu Feb 04 2016 12:42:19 GMT+0000 (UTC)] INFO Joining Room: GENERAL
hubot_1 | [Thu Feb 04 2016 12:42:19 GMT+0000 (UTC)] INFO Joining Room: room1
hubot_1 | [Thu Feb 04 2016 12:42:19 GMT+0000 (UTC)] INFO Joining Room: room2
hubot_1 | [Thu Feb 04 2016 12:42:19 GMT+0000 (UTC)] INFO Joining Room: GENERAL
hubot_1 | [Thu Feb 04 2016 12:42:19 GMT+0000 (UTC)] INFO Joining Room: {rid1}
hubot_1 | [Thu Feb 04 2016 12:42:19 GMT+0000 (UTC)] INFO Joining Room: {rid2}
hubot_1 | [Thu Feb 04 2016 12:42:19 GMT+0000 (UTC)] INFO rid:  [ 'GENERAL', '{rid1}', '{rid2}' ]
```

**Comment by ericlakich** [comment]
Thank you!!! ... Found the issue with your help. 

The problem was that I had set my environment variable for hubot to be ...

- ROCKETCHAT_ROOM=''

... per instructions from https://github.com/RocketChat/hubot-rocketchat/blob/master/README.md

That was causing the blank rid issue so I changed my listing to ...

- ROCKETCHAT_ROOM='general, build'

... and that didn't work because hubot was escaping the quotes and looking for rooms with names \'general and build\'

so I changed my env variable setting to ...

- ROCKETCHAT_ROOM=general,build

... and in the logs I see ...

hubot_1 | [Fri Feb 05 2016 00:18:40 GMT+0000 (UTC)] INFO Joining Room: GENERAL
hubot_1 | [Fri Feb 05 2016 00:18:40 GMT+0000 (UTC)] INFO Joining Room: 6N5oFQEij3XyRQkkn
hubot_1 | [Fri Feb 05 2016 00:18:40 GMT+0000 (UTC)] INFO rid:  [ 'GENERAL', '6N5oFQEij3XyRQkkn' ]

.. which is what I would expect.

Thanks!!!

**Comment by tholu** [comment]
Great, happy botting! :+1:
