### ISSUE TITLE
LISTEN_ON_ALL_PUBLIC not working

### ISSUE THREAD

**Issue by rcaferati** [RocketChat/hubot-rocketchat#81]
The LISTEN_ON_ALL_PUBLIC variable is not affecting the hubot behavior.

The ROCKETCHAT_ROOM is defaulting to GENERAL, which is strange as in the documentation it's stating that it should not be present when setting the LISTEN_ON_ALL_PUBLIC variable. Also, if ROCKETCHAT_ROOM defaults to GENERAL and the instance does not have the general room it will probably create it. Which is not the intended behaviour.

**Comment by rcaferati** [comment]
@engelgabriel: we should also think about that LISTEN_ON_ALL_SIGNED_CHANNELS thing.

**Comment by Sing-Li** [comment]
This is a tough one.  The bug can be fixed quickly enough, but defaulting to GENERAL is very desirable - because 90% of our users will just run the server with everything default -- and GENERAL is where they are expecting to be able to test their bot in.

**Comment by Sing-Li** [comment]
LISTEN_ON_ALL_PUBLIC will work if you set `ROCKET_CHATROOM=`

Also, LISTEN_ON_ALL_PUBLIC also activates DM - so no need to set both.  When doing DM, remember to address the bot - i.e. `bot pug me` instead of `pug me`.

Updating the doc and closing this ticket.

Please open another ticket if you want to change the default GENERAL channel.

**Comment by viking225** [comment]
Hello i have exactly the same problem my bot is responding to channel where he have been invited, even though i set the env variable LISTEN_ON_ALL_PUBLIC to false, any idea ? I will also ask the question on the git, the issues #68 and #74 didn't quite help me

![image](https://user-images.githubusercontent.com/10079913/27124654-13efb944-50f2-11e7-9987-3283a6b7cfe0.png)

**Comment by geekgonecrazy** [comment]
you'll need to actually set that to true, unless you are specifically setting ROCKETCHAT_ROOM to the rooms the bot is supposed to respond to.

**Comment by vladblindu** [comment]
Hey guys, in august 2023 I have the same problem. My bot responds on every public channel.
How can I stop this behaviour?
