### ISSUE TITLE
Add sendPrivate:

### ISSUE THREAD

**Issue by pcarn** [RocketChat/hubot-rocketchat#82]
hubot-irc has a sendPrivate function that sends a private message to the user who sent the command. 

When hubot scripts use this, it does nothing on rocketchat.

**Comment by richardwlu** [comment]
I would be interested in this also. There are times where it is best that hubot sends a Direct Message rather than spam a chatroom.

**Comment by pcarn** [comment]
Agreed

**Comment by geekgonecrazy** [comment]
@pcarn / @richardwlu is this something that's standard to hubot?  I have no objection to adding it.. Just we might want to get this added to the hubot spec if not

**Comment by Sing-Li** [comment]
Each chat system that hubot works with is slightly different - and the hubot API attempts to abstract it away, so you can use your script with any chat.

With Rocket.Chat, you ALREADY can Direct Message with your bot.  Just click on the bot's avatar to create a room where only you and bot can converse in private.

I would suggest that the above is sufficient.

**Comment by pcarn** [comment]
The reason why this is needed is that many hubot scripts call a sendPrivate function, that lets the bot reply to a command with a message to the user instead of spamming the entire channel.

Right now that doesn't work, because the function isn't defined.

**Comment by Sing-Li** [comment]
Again.  Each chat system has its own personality and behavior.  

With Rocket.Chat - private, single-user-targeted messages DO NOT appear in-line with regular message flow.  It happens in a completely separate Direct Message private 'room'.    You _**cannot**__ spam an entire channel when you send a private message to the bot in that private one-on-one "room".

**Comment by engelgabriel** [comment]
Let's implement the `sendPrivate` as sending a PM

**Comment by pcarn** [comment]
@Sing-Li - The use case for this is that if a user types a command in a public channel that hubot would give a long response to, if the script uses sendPrivate, it would open a direct message to the user instead of replying in the public channel. This is how sendPrivate works for hubot in irc.

This isn't referring to when the command comes from a private message, it's when it comes from a channel, but the script doesn't want to flood the channel with a long message.

**Comment by Sing-Li** [comment]
@pcarn - Thanks.  I see.   So in the case of Rocket.Chat - the Direct Message private 'room' will be created by the bot's reply if not already existing, and all the sendPrivate message(s) from the bot will be sent there.

**Comment by pcarn** [comment]
Yes, that's correct. Thanks, this will be useful since many scripts use the sendPrivate function.

**Comment by richardwlu** [comment]
Would the ability to specify users within the sendPrivate() be possible. We have scripts that that we plan on creating that will update users based on a queue or timer they create.

As a side question - will the hubot-rocketchat allow for an 'announce' feature to allow for a script to send a message to a list of channels? For example, we would like users in the channel "support" to receive a message from hubot of when a ticket is created but not to any other channels.

**Comment by engelgabriel** [comment]
@richardwlu both will be possible.

**Comment by richardwlu** [comment]
I like the sound of that :smile:

**Comment by pcarn** [comment]
Here is the hubot-irc implementation of it. Calling it the same way should hopefully mirror the same behavior.
https://github.com/nandub/hubot-irc/blob/master/src/irc.coffee#L29

**Comment by NioTeX** [comment]
https://github.com/RocketChat/hubot-rocketchat/pull/101

**Comment by geekgonecrazy** [comment]
as @NioTeX said this is working.  Thanks again for the pull request :+1:

**Comment by richardwlu** [comment]
Has there been an implementation to allow for messages to be sent to a list of specific channels?

**Comment by geekgonecrazy** [comment]
@richardwlu there has not.  Please open a new ticket to discuss that

**Comment by NioTeX** [comment]
@richardwlu It has not been, but you can do that with:
```coffee
robot.respond /send to rooms/i, (res) ->
   res.envelope.room = "room1"
   res.send "Hello room1"
   res.envelope.room = "room2"
   res.send "Hello room2"
```
Somebody could probably implement this as a function ( sendToRoom )
