### ISSUE TITLE
hubot-gitlab-hooks not working

### ISSUE THREAD

**Issue by zaubererty** [RocketChat/hubot-rocketchat#83]
I have installed this hubot integration to rocket.chat and it works so far grate, but the gitlab integration needs to access the bot by a html request.
Cause the the container does not expose any port are I'm not able to call the bot back.

Should I submit a pull request for the expose on port 80?

Greetings  Thomas

**Comment by geekgonecrazy** [comment]
@zaubererty hubot by default listens on port 8080.

So the URL you would hit would be something like:

`localhost:8080/hubot/gh-repo-events`

I'm not 100% sure what the url is for the gitlab bot.  You'll need to take a look in the script for a line that contains: `robot.router.post`

**Comment by zaubererty** [comment]
8080 did the trick

ists /gitlab/web or /gitlab/system
