### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by lazyfrosch** [RocketChat/hubot-rocketchat#85]
My Rocketchat instance sits behind a SNI webserver.

The hubot hangs in trying to connect to the websocket.

Bug: https://github.com/faye/faye-websocket-node/pull/50
Blocked by faye-websocket update and release of asteroid: https://github.com/mondora/asteroid/pull/85

**Comment by engelgabriel** [comment]
Thanks @lazyfrosch 

Can you help us fix it own our fork https://github.com/RocketChat/asteroid

Let's not wait for the PR to be approved.

**Comment by engelgabriel** [comment]
Can you help test with the latest changes? It may be fixed now already.

**Comment by lazyfrosch** [comment]
I don't have a hubot running currently, the problem is that faye is not at all setting server_name for TLS, and nor is the REST client behind it. There is no default setting in Node for it either, so you would have to set the server_name unless the lib does not set a default.

Its rather nasty.

**Comment by geekgonecrazy** [comment]
Any change with this?

**Comment by lazyfrosch** [comment]
Sorry can't help here

**Comment by geekgonecrazy** [comment]
@lazyfrosch so just to confirm..  Were you able to see if the changes made fixed the problem?  Or still not making use of hubot any longer?  Just want to make sure to know the next step on this issue. :smile:

**Comment by lazyfrosch** [comment]
@geekgonecrazy not running Hubot or Rocketchat at the moment, sorry :wink:

**Comment by geekgonecrazy** [comment]
@lazyfrosch no problem.  Just wanted to make sure 👍

**Comment by Guidonet** [comment]
This is still an issue as far as i can tell.  Using RC 0.61.2 with Rancher 1.6.14 with their HAproxy load balancers.  Have certs for several sites in those LB's, including one for our rc implementation.  But no matter what, when connecting, i get presented the first cert i had added.  They have a note at the bottom of their lb saying: 
"Note: Some older SSL/TLS clients do not support Server Name Indication (SNI); these clients will always be offered the main Certificate Modern clients will be offered an appropriate certificate from the Alternate Certificates list if a match is found."

Is this something that can be resolved?

**Comment by timkinnane** [comment]
@Guidonet can you please submit an issue on our [new SDK](https://github.com/RocketChat/Rocket.Chat.js.SDK). I would, but I don't fully understand the scenario. The SDK now handles the connection to Rocket.Chat and will be implemented by more than just Hubot, so it's the best place to fix this. It is also unit tested, so we can potentially test this in isolation.
