### ISSUE TITLE
Handling Multiple BOT instances 

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/hubot-rocketchat#88]
Create private channels A, B, C, D, E, F:
- bot ONE listening to A, B, C 
- bot TWO listening to D, E, F 

And both bots logged in as same user.

BUG -> both bot ONE and TWO sees every message sent in A, B, C, D, E, and F

**Comment by Sing-Li** [comment]
This may be tricky to handle because the behavior described is EXACTLY what is expected to happen with a real user.  And a bot currently appears as a real user to the Rocket.Chat server.

An upcoming Bots Manager on the server side _might_ be the answer.

**Comment by or1gb1u3** [comment]
why should both bots be logged in as the same user? I think if you are trying to separate information into multiple channels you may want to use multiple bots with different user accounts, and you could have them respond to the same trigger.

**Comment by unixfox** [comment]
Great idea ! :+1:

**Comment by geekgonecrazy** [comment]
Just as a note on this one... You could technically log all bots in as the same user.  We currently ignore any messages from the user the bot is logged into.  So there shouldn't be clashes between bots if logged in as the same user.

**Comment by timkinnane** [comment]
Closing this as the suggestions above provide workable solution. I would generally discourage multiple bots in one account, but it can be done. Could also filter within each bot's scripts to only respond in specific rooms.
