### ISSUE TITLE
Use of other external hubot scripts with timebased actions

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/hubot-rocketchat#96]
Hey Guys,

i have installed this script in my hubot: https://github.com/jeffbyrnes/hubot-forecast

The normal "bot weather" command is working and my hubot got the forecast for me. But can you say if the time based actions / posting in other rooms work, too?

Thx a ton!

Greez 
TheReal

**Comment by Sing-Li** [comment]
@TheReal1604   Can you please clarify:   "But can you say if the time based actions / posting in other rooms work, too?"   -  Thanks.

**Comment by TheReal1604** [comment]
Hey SingLi, 

I tested some other external scripts, which do a time based action in a explicit configurable room. This scripts have the same issue, the manual command work, but the automatic time based actions not. 

I have configured my hubot to listen all public rooms. Is there the problem? Also I tested the script "hubot-shy" - the hubot answers me with an OK" but not posting my text in the channel I told him. In addition, my installation is completely in docker containers. 

The logs of the hubot container did not show any errors. (docker logs rocketchat_hubot_1)

Thx in advance.

**Comment by geekgonecrazy** [comment]
This might be a case of the channel needing to be looked up.  The method I think expects our id's still instead of channel name.

Try getting the channel id like found in this gif:

https://cloud.githubusercontent.com/assets/51996/10064636/1a6125f8-6240-11e5-92cc-d3d8606117e4.gif

If passing that instead of the channel name works then my theory is correct.

**Comment by TheReal1604** [comment]
I have changed the setting, so just waiting for some weather changes :-P.

**Comment by TheReal1604** [comment]
Okay, seems the developer and i have to test it later.. it could be that he broke the script by refactoring the scripts.. hmpf.

Thx for your help!

**Comment by geekgonecrazy** [comment]
@TheReal1604 ok, let me know how the test turns out.  I believe it takes the channel name.. But if not that could be your issue.

**Comment by geekgonecrazy** [comment]
@TheReal1604 you never did report how your test went 😉 

Going to go ahead and close this issue though since this is more an informational query.

**Comment by TheReal1604** [comment]
@geekgonecrazy This issue was out of my scope right now, sry for that! The developer of this script doesn't react on my issues so.. I find other ways to do what I need. Thanks for closing it!
